### ISSUE TITLE
URL expired when downloading a second file

### ISSUE THREAD

**Issue by andrewmoreau1996** [openaudible/openaudible#874] opened 2022-02-15 17:47 UTC
![image](https://user-images.githubusercontent.com/22079554/154119014-a5670ff1-6a8e-45a4-ae27-db09ce2fcd8e.png)

**How to reproduce:**
1. Full audible library sync
2. Download a title
3. attempt to download a second title (should throw an error about Expired URL in the state field)

**Work Around:**
- redo full audible library sync (this has to be repeated after each download)
- download a title

**Comment by openaudible** [comment] 2022-02-15 18:07
That is an audible api response. Maybe something is changing. What audible region are you in?

Can you repeat your steps above and send a bug report from the Help menu?

**Comment by Trytodosth** [comment] 2022-02-15 20:10
Hi, similar issue here and can't upload the bug report because of an internal error message:
![image](https://user-images.githubusercontent.com/22024737/154140923-ee98d4ba-89a8-409a-915d-a075bba8506b.png)

Error itself:
When trying to download recently added books, I have the following message "Download error: Download url is expired for XXXX".
It's not all the books but some. I tried restarting the app and re-syncing the Audible Library.
My Audible account is in France region (although download from Switzerland as usual).

Thanks

**Comment by openaudible** [comment] 2022-02-15 20:45
Oh, that message @Trytodosth is because you aren't using the latest release version, but your report was accepted.. 
Working on a fix.

**Comment by Trytodosth** [comment] 2022-02-15 20:47
Yeah I use to tool on a regular basis but did not update before my license expired in January :/
Thanks. Will the fix require an update by the way?

**Comment by openaudible** [comment] 2022-02-15 21:23
@Trytodosth Yes.

**Comment by inkDaemonNine13** [comment] 2022-02-15 22:22
I can confirm that this is also happening for the US region (with latest release).

**Comment by inkDaemonNine13** [comment] 2022-02-15 22:34
@openaudible I also get the below error sporadically. Sometimes it finishes the download, sometimes it doesn't. This can be with short or long length books, but seems to be more common with the longer length ones.

INFO: DownloadQueue error processing Download [BOOK NAME]
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 190,332,937; received: 164,548,645)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.openaudible.util.CopyWithProgress.copyWithProgress(CopyWithProgress.java:80)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:108)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:211)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:507)

**Comment by andrewmoreau1996** [comment] 2022-02-16 01:53
so with a bit more testing, if you do a full audible library sync then wait like a minute then try to download it will also say timed out URL. Are you using the same session to fetch library sync and other download actions after that? If so, then I would send a new request for each download instead of continuing to use the same session? I feel like session is the wrong word. maybe socket?

**Comment by openaudible** [comment] 2022-02-16 04:30
Looks like a change to make the old download links less permanent.
There is a new beta that should help. Please report back.
https://openaudible.org/beta

**Comment by andrewmoreau1996** [comment] 2022-02-16 04:48
beta changes seemed to of fixed it.

**Comment by openaudible** [comment] 2022-02-17 01:41
Fixed in 3.5

**Closed by openaudible** 2022-02-17 01:41 UTC
