### ISSUE TITLE
Not seeing recent books

### ISSUE THREAD

**Issue by bigbosst** [openaudible/openaudible#1267] opened 2023-09-23 02:22 UTC
Books purchased in the last month are not showing in my library in open audible, so can not be downloaded. I have run the quick and full sync. They are visible on the audible website etc. but don't show in OpenAudible anywhere.

**Comment by openaudible** [comment] 2023-09-23 04:07
Make sure you are connected to audible. Make sure you are connected using the right account. Try logging out and re-logging in (especially if you have multiple accounts.) Make sure you haven't "ignored" the books.

**Comment by bigbosst** [comment] 2023-09-23 04:33
Ok so they syncs weren't giving errors, however logging out of audible and back in got the books to show up. Not sure why they syncs would wouldn't fail, but still not inventory new books.

**Comment by brndnmtthws** [comment] 2023-09-23 16:12
I recently had this issue, logging out and logging back in to audible fixed it. [Here's the error I got in the console](https://gist.github.com/brndnmtthws/7260d86cf059db2ab8928a573d614f77) if that helps.

**Comment by cdegrassi** [comment] 2023-09-23 16:16
Hello, I am having the same issue with the latest version

**Comment by MrSchoolcraft** [comment] 2023-09-23 21:18
confirmed the logout and in fixed this issue for me as well. Thank you!

**Comment by openaudible** [comment] 2023-09-24 00:32
Hm. Would like to see the console log to maybe recognize this better... Thanks for the heads up. Releasing a new version soon..

**Comment by MBell112** [comment] 2023-09-24 10:21
Experienced the same, solved the same way, with logging out then in

**Comment by RudolfSch** [comment] 2023-09-24 19:57
I had a similar issue but logging out and then trying logging resulted in multiple crashes. 2 times when I logged out and selected Secure Webbrowser... (I have sent 2 times the report to Apple). 

Another time when I tried the OpenAudible-Login:
Sep. 24, 2023 9:46:06 NACHM. org.openaudible.desktop.swt.manager.login.LoginDialog loadCaptcha
INFORMATION: Load captcha:https://images-na.ssl-images-amazon.com/captcha/huyzhwry/Captcha_ghnoqcuqgg.jpg
Sep. 24, 2023 9:46:06 NACHM. org.openaudible.desktop.swt.manager.login.LoginDialog loadCaptcha
INFORMATION: captcha image=/Users/rudolf/Library/OpenAudible/tmp/captcha.jpg length=5582
Sep. 24, 2023 9:46:06 NACHM. org.openaudible.desktop.swt.manager.views.AnimatedImageLabel <init>
INFORMATION: captcha animation frames:1
Sep. 24, 2023 9:46:14 NACHM. org.openaudible.audible.api.login.Login validateFormURL
INFORMATION: org.openaudible.audible.api.login.Login@4a3329b9 validateFormURL=/errors/validateCaptcha location=
Sep. 24, 2023 9:46:14 NACHM. org.openaudible.audible.api.login.Login validateFormURL
WARNUNG: relative url from takeInteraction:/errors/validateCaptcha
Sep. 24, 2023 9:46:14 NACHM. org.openaudible.audible.api.login.Login validateFormURL
SCHWERWIEGEND: unexpected error parsing url:  /errors/validateCaptcha
java.lang.Exception: url relative and location not set
	at org.openaudible.audible.api.login.Login.validateFormURL(Login.java:896)
	at org.openaudible.audible.api.login.Login.loginDefault(Login.java:853)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.loginWithoutBrowser(LoginGUI.java:43)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:27)

But this seems to be another story which also should be fixed.

However I found out that the metadata for new books ("Erste Person Singular" and ":Das Ende des Alterns") are processed but then the new books don't show up in the list even after several tries of full and quick sync.

INFORMATION: Starting job MetaJob Erste Person Singular MetaQueue size:2 remain:0 success:0 fail:0 threads:2 jobs:0
Sep. 24, 2023 9:21:53 NACHM. org.openaudible.util.queues.ThreadedQueue jobStarted
INFORMATION: MetaQueue started:Das Ende des Alterns MetaQueue size:2 remain:0 success:0 fail:0 threads:2 jobs:1
Sep. 24, 2023 9:21:53 NACHM. org.openaudible.util.queues.ThreadedQueue jobStarted
INFORMATION: MetaQueue started:Erste Person Singular MetaQueue size:2 remain:0 success:0 fail:0 threads:2 jobs:2
Sep. 24, 2023 9:21:54 NACHM. org.openaudible.audible.api.API getChapters
INFORMATION: No chapter data found for asin 3844926925 {
 "response_groups": [
  "last_position_heard",
  "content_url",
  "content_reference"
 ],
 "content_metadata": {
  "last_position_heard": {"status": "DoesNotExist"},
  "content_reference": {
   "file_version": "1",
   "acr": "CR!MY5MSWH4ZN4RHBN4STBFQ9ZS4YZM",
   "codec": "mp4a.40.2",
   "marketplace": "AN7V1F1VY261K",
   "content_format": "M4A_AAX_44_64",
   "tempo": "1.0",
   "asin": "3844926925",
   "sku": "BK_HAMB_003302",
   "version": "39083771",
   "content_size_in_bytes": 139000958
  }
 }
}
Sep. 24, 2023 9:21:54 NACHM. org.openaudible.util.queues.ThreadedQueue jobError
INFORMATION: MetaQueue error processing MetaJob Erste Person Singular item Erste Person Singular
java.lang.Exception: No chapter data found for 3844926925
	at org.openaudible.audible.api.API.getChapters(API.java:240)
	at org.openaudible.audible.LibraryScanner$MetaQueue$MetaJob.processJob(LibraryScanner.java:68)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:567)

**Comment by mdnitoil** [comment] 2023-09-24 20:15
Logged out but cannot log back in.  Either method just hangs indefinitely.  Debian user here.

**Comment by openaudible** [comment] 2023-09-24 21:14
We're seeing an issue with the "no browser" login method. Working on a fix.

**Comment by bilcorry** [comment] 2023-09-25 21:20
Same issue, I had to log out and log back in.

**Comment by openaudible** [comment] 2023-09-26 02:47
If anyone sees this and hasn’t logged out and back in, do a full rescan from the control menu and send a bug report with the name of a missing book. Thanks.

**Comment by KGOrphanides** [comment] 2023-09-26 07:43
I'm having this issue and I've not relogged in to see if it fixes it yet, so I've sent a bug report. I'm on version 3.7.5.
Unfortunately, I didn't realise that pressing enter would send the report, so here is the accompanying text and missing book list:

Missing books from audible library: Pyramids by Terry Pratchett (read by Alfred Enoch et al), Wyrd Sisters by Terry Pratchett (read by Indira Varma), Sourcery by Terry Pratchett (read by Colin Morgan), Ladybird Audio Adventures: Cities Around the World, Ladybird Audio Adventures: Australia. All bought on or after 25-06-2023.

Attempting to send a second bug report throws up:
Error: java.util.zip.ZipException: duplicate entry: books.json

Deleting the zip file from the previous bug report didn't fix this and I don't actually want to delete boots.json and re-create it (although I notice that it hasn't been updated since the 16th of June, despite my refreshing my library.)

**Comment by openaudible** [comment] 2023-09-28 01:26
3.9.0.2+ solves the bug report bug..  But we're only really looking at bugs in 3.9 and higher. 
Beta is best: https://openaudible.org/beta (
I think the no chapters for book error can safely be ignored-- it shouldn't prevent any books not being found. But will check on that for the next beta 3.9.0.3 and make sure it is doing the right thing.

**Comment by KGOrphanides** [comment] 2023-09-28 08:12
Can confirm that upgrading to the latest beta resolved the issue for me.

**Closed** 2023-10-06 00:04 UTC
