### ISSUE TITLE
Errore durante il download

### ISSUE THREAD

**Issue by terrry666** [openaudible/openaudible#978] opened 2022-07-20 19:51 UTC
Salve, nonostante io sia collegato correttamente con il mio account audible, ricevo il seguente errore:

Errore durante il download: http error getting: https://api.audible.it/1.0/content/B0B68Y1HH6/licenserequest reason: Bad Request

Cosa significa?
Ho controllato e la mia licenza è ancora valida. Cosa succede?

**Comment by Cinnamoni** [comment] 2022-07-20 20:25
It's related to this bug caused by Audible API changes: 
https://github.com/rmcrackan/Libation/commit/7f086aeaacf96a20e16ce791cf6a34a2227448b5

**Comment by terrry666** [comment] 2022-07-20 20:38
Grazie mille per la risposta.
Esiste un rimedio attualmente o devo solo attendere che venga sistemato il bug?
E se sono costretta ad attendere, generalmente in quanto tempo vengono risolti questo tipo di bug? Giorni o settimane?

**Comment by openaudible** [comment] 2022-07-20 23:16
Thanks for the heads up, @Cinnamoni   
Will build a beta to attempt to fix this.

**Comment by openaudible** [comment] 2022-07-22 01:02
Please try the beta and report back...
https://openaudible.org/beta

**Comment by blurfl** [comment] 2022-07-22 03:13
This beta doesn't seem to correctly read books.json that was written by version 3.5.6. On startup the beta shows zero values for all fields except M4B files, which the beta correctly reports. If I then quit the beta without connecting to Audible, it writes a 2-byte-long file '[]' for books.json which cannot be as intended.
 I quit the beta, restored the v3.5.6 books.json file and ran a quick library sync using this beta and it mistakenly marked 39 of the books as needing to be downloaded although before the quick sync it showed none needing download.
 Restoring books.json to a copy from before the beta and running version 3.5.6 correctly shows no books requiring download.

**Comment by openaudible** [comment] 2022-07-22 04:56
Thank you @blurfl . Removing beta and will try to fix. Looks like we mixed up some of the unfinished dev code with the beta fix. Sorry for the trouble... and thank you for the report.

**Comment by openaudible** [comment] 2022-07-22 16:49
Hmm. I was unable to reproduce that. And it looks like the version just has one minor change from the previous version. Strange. Feel free to Send me a log if it happens again. 

I reposted the beta and standard disclaimer of making a backup apply.

**Comment by paolomulas** [comment] 2022-07-24 07:00
hello, I just sent you the log error trough the bug notification action on the beta version 3.5.6.1

this is the response 
Login failed > error licencerequest reason:Bad Request


![open_audible_bad_request_on_login](https://user-images.githubusercontent.com/202389/180636284-2fae1aa7-fcd5-4383-94dc-95d1ba2fc6d2.jpg)

**Comment by openaudible** [comment] 2022-07-25 03:03
Ok. Should be fixed in beta 2. 
https://openaudible.org/beta

**Comment by terrry666** [comment] 2022-07-25 06:35
> Ok. Should be fixed in beta 2. https://openaudible.org/beta

Sembra funzionare tutto correttamente ora, grazie mille

**Comment by paolomulas** [comment] 2022-07-25 08:30
> Ok. Should be fixed in beta 2. https://openaudible.org/beta

great! it works perfect 
thanks

**Comment by openaudible** [comment] 2022-07-25 13:12
Thanks for the report. Will update the production app.

**Comment by openaudible** [comment] 2022-07-25 21:56
Fixed in 3.5.7

**Closed by openaudible** 2022-07-25 21:56 UTC
