### ISSUE TITLE
Cover art occasionally does not attach to converted files

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1418] opened 2024-06-19 11:03 UTC
Here is something that occasionally happens in OpenAudible, including version 2.22 . On occassion, the cover art isn't attached to the converted MP3/M4B file. This just happened when I converted B01MFAPPOD - Soulbound - The Return of the Elves Series, Book 1, and happens so rarely I'm not able to detect a pattern. Here is a screenshot of the in OpenAudible showing that the cover exists:

![image](https://github.com/openaudible/openaudible/assets/6700159/082ccadf-7a76-4ef7-b438-14dc5a0e9c74)

But for the actual M4B file, no cover art:

![image](https://github.com/openaudible/openaudible/assets/6700159/4bd39a1c-8401-4e79-b5e4-cae8dc1fbfb9)

Log file: [Log File.zip](https://github.com/user-attachments/files/15899757/Log.File.zip)

**Comment by ZLoth** [comment] 2024-06-19 11:12
Here is a second set of logs, this time without splitting the file. Same thing. [Log File.zip](https://github.com/user-attachments/files/15899885/Log.File.zip)

**Comment by ZLoth** [comment] 2024-06-23 18:27
Another title here... Life on the Mississippi [Blackstone] - ASIN: B004GVNIEY:

![Mp3tag 2024-06-23 13-22-08](https://github.com/openaudible/openaudible/assets/6700159/b808c38b-134f-403b-9390-28f2098999a8)

![mpc-hc64 2024-06-23 13-22-19](https://github.com/openaudible/openaudible/assets/6700159/eae1c7e8-80e0-43d5-8346-053cf283348b)

[Log File.zip](https://github.com/user-attachments/files/15945618/Log.File.zip)

**Comment by ZLoth** [comment] 2024-06-23 20:56
Another one.... 
[Please Don't Tell My Parents I'm a Supervillain.zip](https://github.com/user-attachments/files/15946104/Please.Don.t.Tell.My.Parents.I.m.a.Supervillain.zip)

**Comment by openaudible** [comment] 2024-06-25 18:06
Hmm. You can delete the mp3 or m4b and re-encode it.. and look at the ffmpeg command we use to attach the image. 
You can also select the book at do a Get Info, then look at the "Book report" tab and look at the ffprobe output. We did have a bug in 4.2.2 that didn't include the full book probe info -- so upgrading to the latest beta might give more details: https://openaudible.org/beta

**Comment by openaudible** [comment] 2024-06-26 22:48
Unable to reproduce.. Feel free to send a sample file to https://openaudible.org/check and we can do a full scan on it.

**Comment by ZLoth** [comment] 2024-07-02 18:29
> Unable to reproduce.. Feel free to send a sample file to https://openaudible.org/check and we can do a full scan on it.

The following files have been uploaded:

* 20,000 Leagues Under the Sea B076HSP1FT.AAX
* Life on the Mississippi [Blackstone].AAX
* Please Don't Tell My Parents I'm a Supervillain.AAX
* Soulbound - The Return of the Elves Series, Book 1.AAX
* We Few - US Special Forces in Vietnam.AAX

Here is the log file from OpenAudible build 4.3.0.1 for win64: 
[OpenAudible build 4.3.0.1 for win64 Log.txt.zip](https://github.com/user-attachments/files/16072870/OpenAudible.build.4.3.0.1.for.win64.Log.txt.zip)

**Comment by openaudible** [comment] 2024-07-02 19:14
Those look like standalone AAX files. Is there an image associated with the file in OpenAudible when you click on the image?
If not, if the books are in your library, you should be able to do a full rescan.
Otherwise, you can click on a book without an image and do a Action: Get Info. Then click on the Autofill button. Then look to see if the image has been filled in.

**Comment by openaudible** [comment] 2024-07-02 20:47
OK. Thanks for the report. I think there is a problem when we convert something that doesn't have an image.. which can happen. 
Stand by.

**Comment by openaudible** [comment] 2024-07-02 21:55
I think we have fixed the issue.
https://openaudible.org/beta
You'll need to delete the m4b/mp3, then re-convert.
Let me know!

**Comment by ZLoth** [comment] 2024-07-02 22:10
I have downloaded OpenAudible build 4.3.0.2 for win64 and can confirm that the five problem titles that I have reported above now have artwork after conversion. This extends through the splitting of the file.

Thank you for resolving this defect. I look forward to the official release.

**Comment by openaudible** [comment] 2024-07-31 03:01
Fixed in latest release. Thank you!

**Closed by openaudible** 2024-07-31 03:01 UTC

**Comment by ZLoth** [comment] 2024-07-31 15:52
Thank you!
