### ISSUE TITLE
Umlaut errors from summary -> comments

### ISSUE THREAD

**Issue by chbks335** [openaudible/openaudible#554] opened 2021-02-07 21:27 UTC
There is an error where some characters are not copied the way they should. It affects mostly the summary text who gets copied to the comments field:

Example for onle letter, in that case ü
Summary:  Ã¼berspannt
Comments: ï¿½ï¿½berspannt (which results in question marks, displayed by VLC)
[umlaut.zip](https://github.com/openaudible/openaudible/files/5940040/umlaut.zip)

In another case the album title was affected too:
[log2.zip](https://github.com/openaudible/openaudible/files/5940100/log2.zip)

Thanks for checking :)

**Comment by openaudible** [comment] 2021-02-10 00:41
Are you using the beta or the regular release? You can try the beta https://openaudible.org/beta

**Comment by chbks335** [comment] 2021-02-13 21:46
Yes, just reconverted one file again with Version 2.4.1.5beta, unfortunately the same error:
![Unbenannt](https://user-images.githubusercontent.com/78326535/107862473-5d319600-6e4d-11eb-90b1-08848271e6e2.JPG)

**Comment by openaudible** [comment] 2021-02-17 05:11
Ok. I found one potential fix. Will send an update when posted. Thank you for the report!

**Comment by openaudible** [comment] 2021-02-19 21:20
Ok. I did some more research. Have some questions.. Trying to figure out where the problems are.

Is the data correct in the application? For instance, does the title display correctly in the application?

1. From the beta, do a "Full Library Rescan"
2. Optionally, delete the mp3 and re-encode the problem book. 
3. Select the problem book (der neue..) 
4. Do a "Actions: Book Report..."

Post results or email them to openaudible at email dot tg.

Need to find out if the problem is in the API, in the AAX file, or only when it converts from AAX to MP3/M4B.

Thanks for any assistance. (The potential fix I had above does not look like it will help much-- but might identify when the question mark character code 65533 is found.)

**Comment by chbks335** [comment] 2021-02-24 11:58
Thank you very much for checking! Have sent the requested file.

**Comment by openaudible** [comment] 2021-02-24 18:10
I got the screenshot, but I didn't see the json "book report"

Can you select that book, then do Bearbeiten: Buchbericht  (Controls: Book Report)

And send me the "json" output of that as a reply to this email? It should get displayed in the browser window.

FYI, I tried to reply to your email and I got a bounce.

**Comment by chbks335** [comment] 2021-02-26 17:32
Ah, i didn't see the json, because OpenAudible was running.  Have sent you now the full content of the directory.
Thanks for checking

**Comment by openaudible** [comment] 2021-02-27 03:26
Any chance you can upload the meta data for the AAX file to: https://openaudible.org/check.html?
If you emailed the json, could you please resend it?

**Comment by chbks335** [comment] 2021-02-27 12:58
ok. Check has been uplaoded and a new conversion has been done with the new beta Version. All the Files within the tmp Directory have been sent via WeTransfer. Thank you!

**Comment by openaudible** [comment] 2021-02-28 04:19
Thanks. It appears that the meta data in the AAX is not encoded as UTF-8, which is the expected "standard" for ffmpeg. I'm not sure what charset is being used. Will need to investigate a little more.

**Comment by chbks335** [comment] 2021-02-28 19:43
Thank you! 👍

**Comment by openaudible** [comment] 2021-03-25 01:02
I made a fix to override the tags that are included in the AAX to use what is obtained from your library data.
If you wanted to take a look, I'd be grateful. https://openaudible.org/beta

**Comment by chbks335** [comment] 2021-03-29 20:35
Hi!
Unfortunately the problem still exists, however the Log-Files are different this time. At some points the chars are displayed correctly, just not for the converted files (m4a/m4b). Have sent you the logs via WeTransfer.
Thank you! :)

**Comment by openaudible** [comment] 2021-07-30 03:21
This may be fixed in the latest beta... You'll need to delete your m4b files, do a full library rescan, then re-encode as m4b or mp3. 
https://openaudible.org/beta
Let me know!

**Closed by openaudible** 2021-07-30 03:21 UTC

**Comment by chbks335** [comment] 2021-08-11 14:23
Hey!
Thank you for the fix: it worked! :)

**Comment by openaudible** [comment] 2021-08-11 18:03
Good to hear!
