### ISSUE TITLE
Book download and conversion - author's name neither in filename nor in separate folder

### ISSUE THREAD

**Issue by francwalter** [openaudible/openaudible#1479] opened 2024-11-14 07:56 UTC
Hallo

I created an issue years ago: #703 where I noticed that on conversion to **mp3** and split into chapters, the user could not select any own fields (authors name, audiobook name etc.). I need to add them later manually or with other tools (Mp3tag, etc. e.g.).

This issue was closed unsolved, the dev said that it will be on a Feature Request List (which is, if existant, only visible to himself).

I think about buying again the license, but I want to be sure that this feature is implemented now. I still have OpenAudible 3.5.9 and at the moment there is 4.4.8

Is that feature implemented at last? Is there a dialog now for conversion to **mp3** and split or is it still without any possibility of user settings?

Thanks.frank

**Comment by openaudible** [comment] 2024-11-15 16:07
Still not there. The problem is edge cases. For example, in the book "The Greatest Science Fiction Stories of the 20th Century" the author is listed as: 

"Greg Bear, Terry Bisson, David Brin, John W. Campbell, Harlan Ellison, Ursula K. Le Guin, Judith Merrill, Frederik Pohl, Eric Frank Russell, Arthur C. Clarke	David Ackroyd, Wil Wheaton" 

Do you really want that as a file name? The length of the above example is 188 characters and windows has many restrictions on directory name lengths as well as total path length. 

We are making progress on that feature... but if we screw it up, we're going to have a lot of unhappy users. So we have to tread carefully.

**Comment by francwalter** [comment] 2024-11-16 06:34
Thank you for the answer! 
That's a bit what I thought, I stick to 3.5.9 then. 

About your example: there are maybe such long author or title tags, but most of them are not that long and it is possible to cut them, if too long, avoiding too long file or dir names.
If there were a user dialog, the user could choose how to cut. 
Could be a setting to check with our without user interaction etc.

But I see, it's too much work for you and other things are maybe more important. 

I will continue to rename myself when I download a book, which happens not that often anyway.

**Comment by openaudible** [comment] 2024-12-07 15:37
Marked as known feature request. In progress.

**Closed as completed by openaudible** 2024-12-07 15:37 UTC
