### ISSUE TITLE
Broken M1 download link, internal to app and on website.

### ISSUE THREAD

**Issue by the1gofer** [openaudible/openaudible#924] opened 2022-04-15 16:30 UTC
Download link seems to be broken. https://openaudible.org/latest/OpenAudible_mac_aarch64.dmg

**Comment by openaudible** [comment] 2022-04-15 18:00
I assume you're getting a 400 error? This sounds like a duplicate of #923 .... Which we are working on and _thought_ we had a fix for.

**Comment by openaudible** [comment] 2022-04-15 19:02
Finally solved. This was a missing cookie bug... Sorry for the troubles and THANK YOU for the report.

**Closed by openaudible** 2022-04-15 19:02 UTC
