### ISSUE TITLE
Cannot connect to account on Ubuntu 21.10: webkit2gtk-4.0 crash

### ISSUE THREAD

**Issue by kubijo** [openaudible/openaudible#757] opened 2021-11-02 11:09 UTC
![image](https://user-images.githubusercontent.com/11244314/139835820-55cb1073-97f1-4f07-89f1-f14e1d8056f1.png)

**Comment by openaudible** [comment] 2021-11-02 20:13
Webkit can sometimes need an extra update or package to run correctly. But basic ubuntu 21.10 should be fine.. 

Are you able to open the OA Browser without logging in (CTRL-B) ?

You might need to google the stack trace a bit to see if someone has solved the issue. 

You might also get a better error message by running from the command line-- there is a debug.sh in the app dir that should work.

I can try to fire up a VMWare instance, but hoping we can find a solution online by googling the issue.

**Comment by Quildar** [comment] 2021-11-02 23:39
Think I may be having the same issue with Ubuntu 21.10. Sadly I didn't grab a copy of the Ubuntu crash log. Hasn't shown a crash since first attempt. OpenAudible's connect window lets me login the first time. After which when it asks for me to enter the credentials the second time with a captcha, the window only loads this far.
![image](https://user-images.githubusercontent.com/60751569/139966268-5a3cdcb1-6e04-497a-8f8c-7c69e9b92ecc.png)

Can press ctrl-B and login normally. just can't seem to login to connect to OpenAudible.

This is a brand new install after running updates in a VM.

**Comment by Quildar** [comment] 2021-11-03 01:04
Error Log, although not sure this helps. Also this is from another new install. Probably going to try installing a previous version of Ubuntu or possibly webkit. If I can figure out how to downgrade webkit,

> ERROR: apport (pid 2207) Tue Nov  2 17:46:01 2021: called for pid 2164, signal 6, core limit 0, dump mode 1
ERROR: apport (pid 2207) Tue Nov  2 17:46:01 2021: executable: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess (command line "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess 17 41")
ERROR: apport (pid 2207) Tue Nov  2 17:46:01 2021: debug: session gdbus call: (true,)
ERROR: apport (pid 2207) Tue Nov  2 17:46:14 2021: wrote report /var/crash/_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitWebProcess.1000.cras`

**Comment by openaudible** [comment] 2021-11-03 04:53
I spun up a 21.10 VM and was able to reproduce. This is definitely not an area we have any real experience in, apart from googling error messages. 

The only error I saw was: "WebKit wasn't able to find a WebVTT encoder. Not continuing without platform support for subtitles."  which @mavroudis reported here https://github.com/webview/webview/issues/621 

Downgrading and reporting is a reasonable plan. I tried updating the SWT GTK library-- no luck.

Looking for help on this one.

**Comment by openaudible** [comment] 2021-11-03 04:56
@Quildar I think the captcha adds some multimedia that the webkit can't handle and it stops rendering the whole page. 
I did get one crash, but that hasn't happened since doing an apt update

**Comment by Quildar** [comment] 2021-11-03 18:04
Did try it with the previous version of webkit and even spun up Ubuntu 20.04.3 LTS. All had the same issue. Realize this is not OpenAudible's fault. Ended up just spinning up a Windows VM for it. Little more resource intensive but no biggie.

**Comment by openaudible** [comment] 2021-11-09 17:58
This is confirmed. This isn't anything we are likely to be able to debug or fix on our own. Hopefully this affects enough people where a bug report will be posted and fixed by one of the webkit maintainers...  

There is a way to run OpenAudible via a web browser and docker... which spins up a Ubuntu 20.04.
https://hub.docker.com/r/openaudible/openaudible

**Comment by openaudible** [comment] 2021-11-17 03:08
Webkit (browser rendering library) was expecting a gstreamer plugin to do closed captions. Those are in a library considered "bad", which are not included in the latest Ubuntu 21.10. 

``` 
sudo apt install gstreamer1.0-plugins-bad
```

According to GStreamer, Bad Plug-ins is a set of plug-ins that aren't up to par compared to the rest. They might be close to being good quality, but they're missing something - be it a good code review, some documentation, a set of tests, a real live maintainer, or some actual wide use.

But installing gstreamer1.0-plugins-bad should fix the issue. 

Duplicate of #782

**Closed by openaudible** 2021-11-17 03:08 UTC

**Comment by kubijo** [comment] 2021-11-17 10:57
Thank you for further investigation, root cause & it's solution :clap:.
Could this be to dependencies in the deb package to prevent future generations from running into this?

**Comment by openaudible** [comment] 2021-11-17 15:14
I don’t know who is supposed to fix this. Someone needs to update their dependencies, I guess WebKit. 

I reported it to WebKit: https://bugs.webkit.org/show_bug.cgi?id=233230

But my installers don’t know anything about dependencies. We just assume the gui will work. Not sure I can add a dependency without requiring root for install, which I like to avoid. Will try to watch for the error in the app and display a message.

**Comment by MrFly** [comment] 2021-12-07 09:54
Same problem here on Ubuntu 20.04 - gstreamer-plugin-bad was already installed. The browser is broken, at login and any other browser operations.

How to fix / work around it for now? Isn't there a way to use "an other browser"? At this stage openaudible sadly isn't usable at all, if I'm not able to login :-(

**Comment by kubijo** [comment] 2021-12-07 09:59
The docker container is one way ... albeit annoying one.
It is then usable on your base system because that generates a file with stored user session.

**Comment by MrFly** [comment] 2021-12-07 15:30
I'm sorry, but this is not really an option for me. But thanks for the hint @kubijo.

I got this error, but I think it's already known and reflects the mentioned webkit issue:

``
(WebKitWebProcess:85177): Gdk-ERROR **: 16:26:03.543: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 228 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
``
