### ISSUE TITLE
Menu bar shows app is called NewApplication (MacOS Sonoma)

### ISSUE THREAD

**Issue by ahokinson** [openaudible/openaudible#1286] opened 2023-10-05 15:05 UTC
Intermittently, the menu bar on MacOS will display the incorrect name of the application.

<img src="https://github.com/openaudible/openaudible/assets/1762048/0d53edb0-4b05-46ce-8df8-00c65a722773" width=100%>

**Additional info:**

Happening on both my computers. The common factor appears to be Sonoma.

<img src="https://github.com/openaudible/openaudible/assets/1762048/eec3c14e-25b9-42be-a5ce-a7a453365d93" width=25%><img src="https://github.com/openaudible/openaudible/assets/1762048/ea674741-b6f4-4324-95d3-5f8d435ea83e" width=25%><img src="https://github.com/openaudible/openaudible/assets/1762048/272f7063-2ff6-4c49-99dd-dffcff707b5f)" width=50%>

**Comment by openaudible** [comment] 2023-10-05 21:07
That's annoying. Looks like Sonoma broke a few things. I see it has been patched, so will need to update one of our libraries.
https://github.com/eclipse-platform/eclipse.platform.swt/commit/f6ad54f04a5819b067075b09b5de908a4c304b07
Will also try out Sonoma.
Thank you for the report!

**Comment by openaudible** [comment] 2023-10-05 23:26
Confirmed in Sonoma. It does seem to switch to OpenAudible at some point after using the app.. 
This will get fixed when the libraries are updated. But they're not available yet. 
Thanks again for the update.

**Comment by openaudible** [comment] 2023-11-29 17:24
This bug has been fixed by Apple. Updating to Sonoma 14.1 (or higher) fixes the problem. 
Thanks for the report!

**Closed by openaudible** 2023-11-29 17:24 UTC
