### ISSUE TITLE
file naming collision

### ISSUE THREAD

**Issue by aljex** [openaudible/openaudible#127] opened 2019-04-22 21:43 UTC
Title alone is not a good enough file name to avoid collisions. Different books can have the same title. In my case I have one where it is the same original book, but produced by different publishers and performed by different readers.

I see in my aax dir, I have two non-collidng names:
10 to the 16th to 1.1.mp3      23510K   Jan 17 22:48
10 to the 16th to 1.mp3         27460K   Jan 17 22:47

ok so a .1 was added to avoid a collision, but there still is a collision.
I have, somhow, both an mp3 dir and a web/mp3 dir with almost the same contents.
web/mp3 seems like it might be just a new location where everything goes now, because it's files are newer. For most files, there is an identical file in both dirs, and the web/mp3 one is newer. Except another clue suggests the opposite: the mp3 dir has more files. mp3 has everything from web/mp3, plus a few recent purchases. web/mp3 doesn't have anything that's not in mp3.

Anyway, web/mp3 only has a single "10 to the 16th to 1" without the .1, BUT, it's the filesize of the one WITH the .1 from the mp3 directory, and it's more recent.
Look at the fie sizes and times here:

aax:
10 to the 16th to 1.1.AAX           │ 29623K│Jan 17 04:33
10 to the 16th to 1.AAX             │ 32361K│Jan 17 04:18

mp3:
10 to the 16th to 1.1.mp3           │ 23510K│Jan 17 22:48
10 to the 16th to 1.mp3             │ 27460K│Jan 17 22:47

web/mp3:
10 to the 16th to 1.mp3              │ 23510K│Apr  7 17:00

Something is not 100% with the file name strategy yet.

I see that on Jan 17, I must have downloaded and converted both files, and whichever one happened to come 2nd got a .1 appended to it's name to avoid the collision.

Then later, when I downloaded that .1 version again, it did NOT get a .1 appended to it's name this time. So now, that file collides with a different book. If I copied the new mp3 back to my bulk long term NAS storage, it would overwrite a different book and the first book would be lost.

How I ended up with 2 copies of all the same mp3's isn't actually too important for this problem. I definitely changed my config settings a few times while I was working out a method to make OpenAudible portable. I used the trick I descried in another issue to tell java a fake user.home by setting an environment variable, combined with a small launcher script to automatically figure out what that variable should be set to. And Along the way I must have had mp3 pointing one place one day, and then pointing another place another day.

For that matter, that kind of activity (changing those directory settings) should be perfectly legal and allowed for, since they are user-configurable settings.
But that doesn't matter because the same thing could also happen simply by erasing the mp3s to make room one day, and then later downloading the same book. When a book is downloaded and converted, the filenames need to be somehow predictable and consistent from one day to another. Dynamically adding a suffix one day, and then not another day is no good, because here is an example of what can hapen.

I don't know what the most elegant answer is. The Audible book codes probably didn't collid, but they are not human sensible at all. Adding publisher or date data would make the names very long. The audible codes are pretty short, maybe they could be prepended or appended. Too bad there isn't an ISBN, maybe the audible book codes are the closest analog to that, and good enough for this purpose.

Here are these two books in my library:
![Audible_Duplicate_Titles](https://user-images.githubusercontent.com/455568/56529055-24108f00-651e-11e9-9dc4-f82cb4af16c0.png)

And I have captured the "view page source" from this library view. Should I attach that here or email it to you or do you even need it?

btw both of these are no loger available. I can still download them, but they don't come up when you search like buying a new book, and when I click on the titles or pictures, in both cases it says "sorry this book is not available"

That right there is ALL the justification anyone needs to download and convert these books so that they don't disappear after you've paid for them. I have a few books that actually have fully disappeared where I can't even download them. I complained to Audible and they gave me book credits but the books are gone.

**Comment by aljex** [comment] 2019-04-22 21:56
In fact, moving things to storage to make room is exactly how I noticed this. My OpenAudible directory is a whopping 446GB !!! I ran out of room even on my 2T external drive and had to move something off to NAS. Part of that is because I somehow got 2 mp3 dirs, 150GB each, plus the aax dir another 150GB. I was comparing the two mp3 dirs to de-dupe and delete one of them without losing anything.

It shows that, even without the duplicate mp3 dir, and even without retaining the original aax's, even just 150G for the final mp3s is a lot, and deleting stuff and pointing the dirs to other locations is a real need, and has to be allowed for.

**Comment by openaudible** [comment] 2019-04-23 20:11
Duplicate titles should be fine-- collisions will have a numeric suffix on the end. But duplicate mp3 files will cause a problem. 

Hopefully the problem is that you had duplicates, and the new OpenAudible attempts to import all mp3s found in its mp3 directory. But every use case hasn't been tested, of course. 

If you have duplicated mp3's, you should be able to delete (or move) them and restart.. and see what needs to happen. Red dots indicate no aax,mp3, or download link, so can be safely deleted. 
Re-downloading aax and re-converting to MP3 should safely re-create what you need. 
And if you have duplicated aax, that is the same kind of issue.. delete (or move) some or all, restart and re-download if needed. 

Finally, a word on file names: OpenAudible picks a name for each book. After that, the art,mp3, and aax all must use that file name forever. You can't rename those files without causing havoc when a Controls: "Refresh Files" is done (unless you copy the mp3 to another location).
I'm closing this not because it is solved, but because there isn't much I can do except to improve the documentation.

**Closed by openaudible** 2019-04-23 20:11 UTC

**Comment by aljex** [comment] 2019-04-24 05:12
And likewise there is not much more I can do to show you what is wrong with adding a suffix *dynamically*, than show you an actual example of how it creates a collision which results in lost files.

If you want to ignore that, at least you can't say someone never brought it up, in exhaustive detail no less.
