### ISSUE TITLE
linux_rcrack: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by minexew** [openaudible/openaudible#48] opened 2018-10-25 13:47 UTC
I get this error in console when trying to Convert to MP3 on Fedora 28. OpenAudible build 1.2.3 for gtk swt 4763 jvm 1.8.0_181.

Installing `compat-openssl10` doesn't help either, it installs `libcrypto.so.1.0.2o` which is NOT compatible to 1.0.0.

**Comment by openaudible** [comment] 2018-10-25 15:48
Requires a linux/C specialist to statically link the required libraries.  
No time or energy to fix... but will happily accept a Pull Request. #

rcrack is 100% based on: 
https://github.com/inAudible-NG/RainbowCrack-NG

Duplicate of #44

**Comment by minexew** [comment] 2018-10-25 16:07
A statically compiled version of rcrack is available @ http://project-rainbowcrack.com/rainbowcrack-1.7-linux64.zip. It is sufficient to copy the rcrack binary (overwrite linux_rcrack), but the invocation must be changed -- instead of listing all rainbow table file names as arguments to linux_rcrack, just pass the name of the directory that contains them. Then finally openaudible manages to crack the activation code.

**Comment by minexew** [comment] 2018-10-25 16:09
I didn't want to touch any java code so I just called rcrack manually and then created a fake linux_rcrack that passes the expected output to OA.

**Comment by openaudible** [comment] 2018-10-26 23:30
Thanks!

**Comment by openaudible** [comment] 2018-10-30 14:06
OK. Changed to the latest rcrack 1.7 version in 1.2.4. which uses the directory for table arguments.

I tested it on an old fedora vm and still saw a link error. Feel free to report any changes.

**Comment by openaudible** [comment] 2018-11-03 00:00
Posted a new version 1.2.5 with the latest version 1.7 version of rcrack. Please give it a try and comment with success/failure.. if failure, please post any suggestions or console output. I also added a GUI alert for when it fails-- but easier to copy and paste from the console window.

**Closed by openaudible** 2018-11-03 00:00 UTC
Labels: help wanted
