### ISSUE TITLE
Unable to connect to Audible.

### ISSUE THREAD

**Issue by nekoliten** [openaudible/openaudible#626] opened 2021-05-07 14:08 UTC
Since the latest update I'm unable to connect to Audible. 

Not the first time I have issues connecting to Audible after a version update, and usually it has something to the with the built-in browser. Quite frustrating.

The in-app browser loads up the amazon sign-in page, but before I can type in the username and password the window goes blank and unresponsive. 

I've tried both the .deb version as well as the .appimage version.

**Comment by openaudible** [comment] 2021-05-07 14:44
Can you quit OA, attempt to connect, and send a bug report from the About menu?

**Comment by nekoliten** [comment] 2021-05-07 20:22
I've now done as requested.

**Comment by openaudible** [comment] 2021-05-12 18:38
That is weird. Unfortuntaely there wasn't a lot of debugging info to go on.
I added logging info... so please try again. It probably won't be fixed, but hopefully a new bug report will give me the cause.
Let me know when you've submitted a new bug report or if it somehow works.

**Comment by nekoliten** [comment] 2021-05-15 07:12
Alright, submitted another one now.

**Comment by openaudible** [comment] 2021-05-16 21:42
I just saw one old bug report.. but nothing using the https://openaudible.org/beta beta 3.0.2.2 (or higher)
Can you try again and make sure you've entered your user/pass into the audible web page and answered the captcha?
It should "just work" and switch to connected.

**Comment by nekoliten** [comment] 2021-05-17 11:49
I have only tried the latest stable release. Will give the beta version a try. 

As for entering the user/pass into audible, as I wrote the in-app browser crashes before I can do that. Also when trying other webpages.

**Comment by openaudible** [comment] 2021-05-17 20:05
You're saying the browser crashes... What does that mean exactly? The browser window closes? The whole app crashes? 

Can you use the built-in browser (CTRL-B) and log into Audible? You're on linux, and some variants of linux are just not very compatible with the built-in browser. You could try updating your OS.. but unfortunately, your latest bug report also had no useful logging information.

**Comment by nekoliten** [comment] 2021-05-18 09:30
When trying to connect to Audible the browser windows open and shows the login screen.

![openaudible_browser_1](https://user-images.githubusercontent.com/58854871/118627536-19dc2000-b7cc-11eb-84be-6f2cfcce0449.png)

As soon as I click anywhere in the browser it turns "blank"

![openaudible_browser_2](https://user-images.githubusercontent.com/58854871/118627578-2496b500-b7cc-11eb-992b-a085cadcfeaf.png)

If I open the browser with CTRL + B I can type in audible.com in the address field, and it will load the page, but then as soon as I click anywhere in the browser it goes blank as seen in the screenshots above. 

I'm running Pop!_OS 20.04 which us Ubuntu based. Everything is updated to the latest versions. Are there certain packages needed to be installed to get the browser working?

**Comment by openaudible** [comment] 2021-05-18 18:48
PopOS 20.04 is out of date. We did basic testing on 20.10 and found it works. 
Next time, please mention that you're using an unusual OS when posting issues.

**Closed by openaudible** 2021-05-18 18:48 UTC
