### ISSUE TITLE
Fetch Series Titel

### ISSUE THREAD

**Issue by maruerru** [openaudible/openaudible#93] opened 2019-02-15 10:25 UTC
It would be nice if you could fetch the series titel from the audio book page?
The info stands between "Sprecher" (narrator) and "Spieldauer" (length) on the german page.
Great work! Keep going!

**Comment by openaudible** [comment] 2019-02-17 20:26
This would be nice.. However, it is difficult to parse reliably. Will keep it in mind but closing as it is not a bug.

**Closed by openaudible** 2019-02-17 20:26 UTC
