### ISSUE TITLE
exported MP3s are VBR but are missing the VBR header

### ISSUE THREAD

**Issue by rsrsps** [openaudible/openaudible#2] opened 2018-03-31 14:34 UTC
just passing this along:

mp3val OR_ORIG_000201.mp3 
Analyzing file "OR_ORIG_000201.mp3"...
WARNING: "/Users/foo/openaudible/working/mp3/OR_ORIG_000201.mp3": VBR detected, but no VBR header is present. Seeking may not work properly.
INFO: "/Users/foo/openaudible/working/mp3/OR_ORIG_000201.mp3": 166427 MPEG frames (MPEG 2 Layer III), +ID3v2, no VBR header
Done!

**Comment by openaudible** [comment] 2018-04-03 05:31
Thank you for the report. Confirmed and fixed in the next version. 
The problem was we were converting the mp3 file directly to stdout (and reading that), instead of letting ffmpeg write the file which allowed ffmpeg to add the xing header.

https://github.com/openaudible/openaudible/commit/14db91ba6963f8bed1719f947a28872aa4df6def

**Closed by openaudible** 2018-04-03 05:31 UTC
