### ISSUE TITLE
Bug: Deleted book from library 

### ISSUE THREAD

**Issue by chompinlynx** [openaudible/openaudible#1419] opened 2024-06-20 22:13 UTC
I deleted a book via openaudible from my library because it did not download the full book. Its Sherlock Holmes and the total length was 62 hrs but only downloaded 9hrs. Then i ran a quick sync to redownload it and it doesnt show up again... 
Expected Result: for the book to reapear in the To Download section.

**Comment by openaudible** [comment] 2024-06-22 03:01
Maybe try a full resync from the control menu.

**Comment by chompinlynx** [comment] 2024-06-22 03:04
I have many book series that I have renamed the titles, so if I do a full library resync it will override all my work (over 40hrs) to rename the series and collections.
This is my dilemma. Can you build in an option to not change the title of the books in a full library resync?

**Comment by openaudible** [comment] 2024-06-22 03:11
It shouldn’t revert the file name. If it does, it’s a bug. You could back up your library using the file manage libraries… and give it a try.

**Comment by chompinlynx** [comment] 2024-06-23 14:27
Im confirming its a bug. Screenshots included. As you can see before full library sync the book titles were all manually renamed by Series / Sequence / title. After full sync it reverts all that back to the title on audible. Super frusturating. 
![a after](https://github.com/openaudible/openaudible/assets/173413107/b115ef30-8e8e-4124-b0e8-096d0df4b7bc)
![h after](https://github.com/openaudible/openaudible/assets/173413107/ff6d4a72-fddb-49ac-80a9-5120e9dc8e6c)
![a before](https://github.com/openaudible/openaudible/assets/173413107/9c01cf4e-e693-459c-81c3-758c9633c20c)
![h before](https://github.com/openaudible/openaudible/assets/173413107/948c9376-8f4d-4cb4-8629-85f6722ffb17)

**Comment by openaudible** [comment] 2024-06-23 14:42
Oh - titles were renamed. Not file names. Yeah that is a known/expected behavior. 

We started a feature that would let you lock tags. It would show as a checkbox in the get info or just be set if you modify a tag. That's the only way we thought of to prevent overwriting tags. 

Will review and see what we can do. You're the first to report having been affected. 

The reason we update them is if audible changes meta data or updates ratings etc we would typically want the updated tags. 

A new locked Boolean may be the only way to prevent this behavior. 

After full rescan did the missing book show up?

**Comment by chompinlynx** [comment] 2024-06-23 15:01
Okay yes that Boolean to lock overrides would be great as audible sometimes even has incorrect series sequence # and non standard series names for popular series.

If you the Boolean can act in the following way, it would be great; Open Full Sync Options > open tag options > (full book list opens in the rows with columns being the metadata tags such as title, series name, narrator etc) in here I could either select all “lock tags/metadata” or just select the whole column of title and series name to lock just those characteristics for all books. If I want certain books to be updated I can just drag and uncheck the “lock tags/metadata” master column for the books.

And it would be great if we can sort by author/series/filename in that option box as that would make this work breezy.

Having to click into the get info of each book to check the “lock metadata” for each book is unusable for many users since we have hundreds if not thousands of books.

**Comment by chompinlynx** [comment] 2024-06-23 15:05
Also yes the missing book appeared in the full library sync, thank you! Could you try and fix the bug where the deleted or ignored books would still be visible in the “ignored” section so that if you changed your mind you can quickly download the individual book without doing a full library sync?

Thanks so much for your responses the past 2 days!

**Comment by openaudible** [comment] 2024-06-26 20:43
A fix has been added to OpenAudible 4.3. 
Go to the File: Manage Libraries. There is now a checkbox that you can uncheck called: Enable Metadata Updates.
Once unchecked, doing a full rescan will not replace your edits.
Hopefully you can restore an older copy of your books.json file and get your edits restored.

**Closed by openaudible** 2024-06-26 20:43 UTC
