### ISSUE TITLE
Severe Error - Create MP3 Got Non-Zero Result:1

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#82] opened 2019-01-14 03:34 UTC
I get the following error with 4 files.  All have properly downloaded aax files, and are properly appearing in the program with their artwork - but the translation to mp3 is not successful.  Two of the 4 cause the program to enter a loop that attempts to create the MP3 over and over, and two just cease after a failed attempt.

Following is the result from the console:

SEVERE: createMP3 got non-zero result:1 
stdErr:Text Media Handler, ...    Stream #0:2: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc, [NULL @ 00000184f7893cc0] Unable to find a suitable output format for 'is', is: Invalid argument
err:Thread[err:  reporter,5,]
Jan 14, 2019 5:23:18 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book to MP3:Candide
java.io.IOException: Conversion got non-zero response:1
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:262)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:335)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:379)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:281)

Jan 14, 2019 5:23:18 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Candide
java.io.IOException: Conversion got non-zero response:1
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:262)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:335)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:379)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:281)

**Comment by openaudible** [comment] 2019-01-14 18:15
Please include the whole ffmpeg command.. you can delete or hide any of the info you like, such as activation_bytes or json64 data, disk paths, etc. or send a bug report from the help menu with the topic mp3 encoding.

**Comment by 1234shai** [comment] 2019-01-16 18:52
Attached is the console text you've asked for.  There's also a strange routine going on where it copies books I've already got, as you'll see at the end.

Jan 16, 2019 8:06:18 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.4.0 for win32 swt 4623 jvm 1.8.0_141
Jan 16, 2019 8:06:18 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.4.0
Jan 16, 2019 8:06:19 PM org.openaudible.Audible checkLibrary
INFO: bl=165, gl=769
Jan 16, 2019 8:06:19 PM org.openaudible.Audible findOrphanedFiles
INFO: orphaned aax files:1
Jan 16, 2019 8:06:19 PM org.openaudible.Audible findOrphanedFiles
INFO:  orphan: RO_A231_000103.AAX
Jan 16, 2019 8:06:19 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -i F:\OpenAudible\aax\RO_A231_000103.AAX -f ffmetadata - 
Jan 16, 2019 8:06:19 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -version 
Jan 16, 2019 8:06:19 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Jan 16, 2019 8:06:24 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jan 16, 2019 8:06:29 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Jan 16, 2019 8:06:29 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert xxx In progress:1 queue: 0
Jan 16, 2019 8:06:29 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:xxx size:0
Jan 16, 2019 8:06:29 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -i F:\OpenAudible\aax\SP_NSTY_000038.AAX 
Jan 16, 2019 8:06:29 PM org.openaudible.convert.ConvertJob createMP3
INFO: creating mp3: xxx to temp file: C:\Users\x\OpenAudible\tmp\SP_NSTY_000038_temp.mp3
Jan 16, 2019 8:06:29 PM org.openaudible.convert.ConvertJob createMP3
INFO: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -activation_bytesxxx-i F:\OpenAudible\aax\SP_NSTY_000038.AAX -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -metadata product_id=SP_NSTY_000038 -metadata asin=B002UZX5LO -metadata narratedBy= -metadata book_genre= -metadata major_brand= -metadata minor_version= -metadata compatible_brands= -metadata "title=xxx" -metadata "author=xxx" -metadata year=2006-11-02 -metadata "comment=Hear from xxx,xxx "xxx"...." -metadata /:\Usersc\x\OpenAudible\tmp\SP_NSTY_000038_temp.mp3 
Jan 16, 2019 8:06:29 PM org.openaudible.convert.ConvertJob createMP3
INFO: createMP3:1
Jan 16, 2019 8:06:29 PM org.openaudible.convert.ConvertJob createMP3
SEVERE: createMP3 got non-zero result:1 
stdErr: Y, ...    comment         : Hxxx,     date            : 2006,   Duration: 01:21:55.25, start: 0.000000, bitrate: 64 kb/s,     Chapter #0:0: start 0.000000, end 4915.246440,     Metadata:,       title           : Chapter 1,     Stream #0:0(eng): Audio: aac (LC) (aavd / 0x64766161), 22050 Hz, stereo, fltp, 62 kb/s (default),     Metadata:,       creation_time   : 2019-01-16 18:01:35,       handler_name    : ?Apple Sound Media Handler,     Stream #0:1(eng): Subtitle: mov_text (text / x) (default),     Metadata:,       creation_time   : 2019-01-16 18:01:35,       handler_name    : ?Apple Text Media Handler,     Stream #0:2: Video: mjpeg, xx(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc, [NULL @ 000002f230a41700] Unable to find a suitable output format for 'xx....', xx....: Invalid argument
err:Thread[err:  reporter,5,]
Jan 16, 2019 8:06:29 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book to MP3:xxx java.io.IOException: Conversion got non-zero response:1
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:262)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:335)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:379)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:281)

Jan 16, 2019 8:06:29 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert xxx
java.io.IOException: Conversion got non-zero response:1
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:262)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:335)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:379)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:281)

Jan 16, 2019 8:06:29 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:xxx queue size:0
Jan 16, 2019 8:06:29 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 2187853 to disk:C:\Users\x\OpenAudible\books.json
Jan 16, 2019 8:06:29 PM org.openaudible.desktop.swt.manager.AudibleGUI exportWebPage
INFO: Book html file is: F:\OpenAudible\Web\index.html url=file:/F:/OpenAudible/Web/index.html
Jan 16, 2019 8:06:29 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting xxx: Conversion got non-zero response:1
Jan 16, 2019 8:06:29 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Replacing book F:\OpenAudible\mp3\OR_ORIG_000226.mp3 with F:\OpenAudible\Web\mp3\Emma.mp3 s1=424121488 s2=349536947 d1=Wed Jan 16 20:05:50 IST 2019 d2=Mon Dec 17 21:56:53 IST 2018
Jan 16, 2019 8:06:29 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Replacing book F:\OpenAudible\mp3\BK_PENG_000607.mp3 with F:\OpenAudible\Web\mp3\On the Road The Original Scroll.mp3 s1=333749250 s2=340408076 d1=Wed Jan 16 20:05:50 IST 2019 d2=Tue Dec 18 03:05:10 IST 2018
Jan 16, 2019 8:06:29 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Replacing book F:\OpenAudible\mp3\BK_GDAN_000470.mp3 with F:\OpenAudible\Web\mp3\Start with Why.mp3 s1=249108218 s2=206366230 d1=Wed Jan 16 20:05:50 IST 2019 d2=Tue Dec 18 04:49:12 IST 2018
Jan 16, 2019 8:06:29 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Replacing book F:\OpenAudible\mp3\BK_GDAN_000062.mp3 with F:\OpenAudible\Web\mp3\The Happiness Hypothesis.mp3 s1=363353391 s2=355852931 d1=Wed Jan 16 20:05:49 IST 2019 d2=Tue Dec 18 03:04:23 IST 2018
Jan 16, 2019 8:06:29 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Replacing book F:\OpenAudible\mp3\BK_RECO_001969.mp3 with F:\OpenAudible\Web\mp3\Treasure Island.mp3 s1=268712747 s2=187842969 d1=Wed Jan 16 20:05:49 IST 2019 d2=Tue Dec 18 06:53:17 IST 2018
Jan 16, 2019 8:06:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by tonyjobson** [comment] 2019-01-22 22:52
same problem for me on 2 books in my library.
i've sent a bug report.

**Comment by tonyjobson** [comment] 2019-01-22 22:56
when i try to run the command in powershell i get a warning that ffmeg isn't an application. I copied a version of the ffmpeg to ffmpeg.exe and then re-ran the command as i was seeing in my console.

The error i got was: 

"
[NULL @ 0000000000151e80] Unable to find a suitable output format for 'invented'

invented: Invalid argument
"

not sure if that helps or means anything to you. 
:)

thanks for your work ont his project!

**Comment by tonyjobson** [comment] 2019-01-22 23:01
The only place I can see the word "invented" is as part of the tag line (description) in the book I'm trying to convert.
I wonder if some of the book's description or tag lines which are used to feed the mp3 metadata have some reserved char in them which is breaking when they are passed through?

**Comment by tonyjobson** [comment] 2019-01-22 23:05
I think i just confirmed my theory.

My second book fails with
"
[NULL @ 00000000028566e0] Unable to find a suitable output format for 'things...
.'
things....: Invalid argument
"
Looking at the command as run I can see the following is being passed accross and the " in the meta data data is breaking your command line being passthrough.

"
"comment=Sinclair Rutherford is a young Seattle cop with a taste for the finer things. Doing menial tasks and getting hassled by superiors he doesn't respect are definitely not "finer things"...." 
"

Is it possible to further sanatise the passed string of the comment field?

**Comment by tonyjobson** [comment] 2019-01-22 23:10
fixed my second book by chaning the " in the comment metadata to _ and it's now converting (via the cmd line)

looking at my first broken book the comment line was:

--->
"comment="Whoever invented skateboarding is a genius. There's only one skater, and his name's Tony Hawk...."
<---
The comment was supposed to be a quote so the open speach mark broke the passed ffmeg command.

removing the speach mark from before the Whoever has fixed this command too.

**Comment by tonyjobson** [comment] 2019-01-23 10:16
@Devs - how is books.json generated? If i edit it, and then reopen the app it gets regenerated.

in my instance the book comment is what's breaking when this is parsed through:

----->

"description":"\"Whoever invented skateboarding is a genius. There\u0027s only one skater, and his name\u0027s Tony Hawk....",

<------
Because my book description contains a quote, it's breaking the ffmeg command.

It seems like you're re-generating the books.json on each start up, but I'm not sure what script is generating the json file.

**Comment by openaudible** [comment] 2019-01-30 01:32
Hey, thanks for the reports. 

Fixed in 1.4.2. 

All quotes in mp3 meta tags are removed when converting.

The json is written to disk on quit.. but you should be able to edit it when the program isn't running.. but it may think it needs reimporting.

**Closed by openaudible** 2019-01-30 01:32 UTC
