### ISSUE TITLE
Split by Chapter Error

### ISSUE THREAD

**Issue by be1993** [openaudible/openaudible#214] opened 2019-10-22 08:24 UTC
Thanks for you excellent work guys.
I tried to split my audiobooks but i get the following error message

A JSONObject text must begin with {at 1[character 2 line 1]

Any idea?

**Comment by openaudible** [comment] 2019-10-22 15:27
Can you paste a little more of the error log from the Console (CTRL-E)? Maybe no chapter data was found, or ffprobe wasn't able to get any useful info from the book you are splitting.

**Comment by wkoot** [comment] 2019-10-23 09:35
Same problem, console log:
```Oct 23, 2019 11:32:34 AM org.openaudible.desktop.swt.manager.SplitJoinGUI _splitBook
INFO: Split directory:/home/user/OpenAudible/mp3/book.mp3
Oct 23, 2019 11:32:34 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /opt/OpenAudible/bin/linux/ffprobe -hide_banner /home/user/OpenAudible/mp3/book.mp3 -show_streams -show_chapters -print_format json 
Oct 23, 2019 11:32:34 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: title:MESSAGE_BOX_TITLE_ERROR body:Error
Oct 23, 2019 11:32:48 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Oct 23, 2019 11:33:07 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Split_By_Chapter
Oct 23, 2019 11:33:12 AM org.openaudible.desktop.swt.manager.SplitJoinGUI _splitBook
INFO: Split source:/home/user/OpenAudible/mp3/book.mp3
Oct 23, 2019 11:33:14 AM org.openaudible.desktop.swt.manager.SplitJoinGUI _splitBook
INFO: Split directory:/home/user/OpenAudible/mp3/book.mp3
Oct 23, 2019 11:33:14 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /opt/OpenAudible/bin/linux/ffprobe -hide_banner /home/user/OpenAudible/mp3/book.mp3 -show_streams -show_chapters -print_format json 
Oct 23, 2019 11:33:14 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: title:MESSAGE_BOX_TITLE_ERROR body:Error```

I'm using `default-jre` (which is currently `openjdk-11-jre`) on Ubuntu 18.04 LTS

**Comment by wkoot** [comment] 2019-10-23 09:39
The problem resides in the packaged `ffprobe`:
```
user@vm:~$ /opt/OpenAudible/bin/linux/ffprobe help
bash: /opt/OpenAudible/bin/linux/ffprobe: cannot execute binary file: Exec format error

user@vm:~$ file /opt/OpenAudible/bin/linux/ffmpeg 
/opt/OpenAudible/bin/linux/ffmpeg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=cb5bc1be1ccd25ff0c82d9d1b1e037f78bbe4eac, stripped

user@vm:~$ file /opt/OpenAudible/bin/linux/ffprobe 
/opt/OpenAudible/bin/linux/ffprobe: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.7.0, BuildID[sha1]=fd5bcc22749983571cd70eb9a058bf044786274e, stripped
```

**Comment by openaudible** [comment] 2019-10-24 19:29
Thanks. I always get confused with ARM vs. Intel.. Will fix for next release. Thanks for the report.

**Comment by wkoot** [comment] 2019-10-25 08:13
If you're working on it anyway, perhaps you can look into shaving a second off the chapter split timestamps. When using the feature now, there seems to be some time lost between start of split and the end of the previous split. I.e. you'll hear "..wo" instead of "chapter two" on file 2 :-)

**Comment by openaudible** [comment] 2019-10-26 19:05
ugh. we use ffprobe to get the chapter timestamps.. and ffmpeg to split them. Are all book chapters wrong? The chapter data comes from the aax file.. and we split the mp3 file. Not sure where the error is getting introduced. Don't have much time to work on this and was worried this would be a feature creep nightmare. Will keep it open.

**Comment by openaudible** [comment] 2019-10-28 22:40
All of the audible books of mine I have tested appear to split just fine.. at least the parts start at the exact right moment and say a nice "chapter X". I will close if I can't reproduce. 

Obviously a new ffprobe will be included in the next version...

**Comment by wkoot** [comment] 2019-10-29 11:51
Might be a bug in my local ffprobe :-) I'll await the next version, thanks for checking

**Comment by openaudible** [comment] 2019-11-02 22:43
It might also be a bug in the audible chapter data.. Make sure the chapters are correct in the Audible application.

**Closed by openaudible** 2019-11-02 22:43 UTC
