### ISSUE TITLE
Unable to connect to audible

### ISSUE THREAD

**Issue by srossan** [openaudible/openaudible#1406] opened 2024-05-31 04:03 UTC
I'm using OpenAudible to sync my library from audible service to my machine.
I've been using the software on Mac and never got any issue.
I switched recently to Linux Mint, and I can't connect to my audible account to sync my library.
When I go to the menu to connect, I answer the various options (Secure Web browser / Select your Audible region, US - audible.com).
A new window opens, from the built-in web browser and nothing happens. I attached a screenshot of the newly created window.
![Screenshot from 2024-05-30 20-56-34](https://github.com/openaudible/openaudible/assets/531291/8cc699ba-59ff-4f04-8ded-c059e7585e3f)

The problem occurred with OpenAudible version 4.1. I upgraded to 4.2, and I have the same issue.
I installed the software through the shell script.

Thanks for looking into it.

**Comment by openaudible** [comment] 2024-05-31 05:01
Not sure what caused that.
Can you try logging in with the Dialogs (not using Web Browser)
Also, you can copy your credentials.json file over from your Mac.

**Comment by kcmccombs** [comment] 2024-06-01 22:26
i am also having this problem just installed on endeavouros arch base the box comes up blank except for the address nothing else any fix for this yet thanks

**Comment by frmieoz** [comment] 2024-06-03 01:16
Having the same problem installing on MX 23.3 Libretto using the shell script.  I am installing as a new installation.

The alternative gives continuous captcha
![Screenshot_20240603_111510](https://github.com/openaudible/openaudible/assets/171524759/b67a9c28-63a1-4209-91a6-ebf457d8804e)

**Comment by kcmccombs** [comment] 2024-06-08 01:28
okay the way i fixed this was i installed another Linux OS which was pop OS installed OA and got it working and then copied all the file from open-audible and placed the on the PC i use as a daily driver this is not the right way but it did work

**Comment by frmieoz** [comment] 2024-06-13 08:05
Updated to 4.2.2 via shell script. No change

**Comment by srossan** [comment] 2024-06-14 22:11
I ended up copying the credentiials.json file, and it fixed my connection
issue.
I'm good now.
Thanks,
-Stephane

**Comment by corigne** [comment] 2024-07-15 14:52
Having the same problem with Arch Linux, using both the shell script and AppImage.

Unable to connect to audible. I get the same blank white window with an address bar at the top of the window when I try to connect via browser. If I try to connect without the browser, I get an endless loop of captcha verifications.

I do not have a machine with Windows or Mac that I can move the credentials file over from.

**Comment by openaudible** [comment] 2024-07-15 17:22
If there is an archlinux iso I can install and reproduce I will try. I know I've tested archlinux in the past and was able to get the browser to work.

**Comment by corigne** [comment] 2024-07-15 20:44
> If there is an archlinux iso I can install and reproduce I will try. I know I've tested archlinux in the past and was able to get the browser to work.

Happy to help where I can. Not this week, but possibly next week I can spend some time with a VM to try for minimum reproducibility. Do you recall what DE / WM you used when you tested on arch? If it helps, I'm using i3.

Here's the segment of stderr after the internal browser attempts to start, if that helps. I'm unfamiliar with the internals, but hopefully this helps.

```
INFO: creating browser of type: SWT.WEBKIT
Jul 15, 2024 3:29:15 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: created browser of type: webkit
Jul 15, 2024 3:29:15 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel enableCover
INFO: set enableCover to false. resize event width=558
src/nv_gbm.c:300: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x816: Permission denied
Jul 15, 2024 3:29:16 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&overrideBaseCountry=true&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&ipRedirectOverride=true&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36303642423936344146343130364431464433313830353345363936454645323033373431314443234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Jul 15, 2024 3:29:16 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&overrideBaseCountry=true&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&ipRedirectOverride=true&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36303642423936344146343130364431464433313830353345363936454645323033373431314443234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Jul 15, 2024 3:29:16 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&overrideBaseCountry=true&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&ipRedirectOverride=true&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36303642423936344146343130364431464433313830353345363936454645323033373431314443234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Jul 15, 2024 3:29:16 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&overrideBaseCountry=true&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&ipRedirectOverride=true&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36303642423936344146343130364431464433313830353345363936454645323033373431314443234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Jul 15, 2024 3:29:16 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent
INFO: browserEvent: changed https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&overrideBaseCountry=true&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&ipRedirectOverride=true&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36303642423936344146343130364431464433313830353345363936454645323033373431314443234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
```

[Here's the full output from stderr](https://github.com/user-attachments/files/16240119/err.txt)
If I can come up with anything I'll check back in.

**Comment by openaudible** [comment] 2024-07-15 23:26
Which UI (desktop manager and display manager) do you have installed? 
Installed with archinstall and installed Gnome and GDM. And it worked as expected.

I googled your error and saw this recommendation:

Try running export WEBKIT_DISABLE_DMABUF_RENDERER=1 and then in the same terminal run the openaudible app.

Asking ChatGPT for help gave some possible solutions:
https://chatgpt.com/share/f10191ce-d226-48a7-800c-b8841f1cb239

**Comment by openaudible** [comment] 2024-07-15 23:56
Claud.AI session:

A user of OpenAudible, a java Eclipse SWT application, on ArchLinux is experiencing a bug when opening the a webkit browser Browser. The following error is reported and need recommendations to fix. This only happens on some installations-- it appears to work on a similar setup using VirtualBox. 
Jul 15, 2024 3:41:00 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: creating browser of type: SWT.WEBKIT
Jul 15, 2024 3:41:01 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: created browser of type: webkit
src/nv_gbm.c:300: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x816: Permission denied
Jul 15, 2024 3:41:01 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent


The error message you've provided indicates a problem with graphics rendering, specifically related to the GBM (Generic Buffer Management) and KMS (Kernel Mode Setting) on the user's ArchLinux system. This issue is preventing the WebKit browser component from initializing properly in the OpenAudible application. Here are some recommendations to address this issue:

Update your system:
sudo pacman -Syu

Check and update graphics drivers: Ensure that the user has the latest graphics drivers installed for their system. For NVIDIA GPUs, they should use the proprietary NVIDIA drivers.

sudo pacman -Syu nvidia
For AMD or Intel GPUs, update the mesa package:

sudo pacman -Syu mesa
Verify user permissions: The "Permission denied" errors suggest that the user might not have the necessary permissions to access certain hardware features. Ensure that the user is a member of the "video" and "input" groups:

sudo usermod -aG video,input $USER
After making this change, the user should log out and log back in for the changes to take effect.
Check and update SWT and WebKit-related packages: Ensure that the necessary SWT and WebKit dependencies are up-to-date:

sudo pacman -Syu webkit2gtk

Investigate hardware acceleration settings: Try disabling hardware acceleration for the WebKit component. This might be achievable through a configuration file or command-line option for OpenAudible, if available.
File system permissions: Ensure that the user has the necessary read and write permissions in the directory where OpenAudible is installed and where it stores its data.
Kernel parameters: In some cases, adding certain kernel parameters might help. The user could try adding nvidia-drm.modeset=1 to their kernel parameters if they're using an NVIDIA GPU.

**Comment by corigne** [comment] 2024-07-16 15:34
> Which UI (desktop manager and display manager) do you have installed? Installed with archinstall and installed Gnome and GDM. And it worked as expected.
> 
> I googled your error and saw this recommendation:
> 
> Try running export WEBKIT_DISABLE_DMABUF_RENDERER=1 and then in the same terminal run the openaudible app.

This worked. I will probably have to do some digging to figure out what specifically is the issue, but on a cursory level I think it's nvidia driver related, and it may be due to the GBM backend not being set in the system environment. I will have to experiment and see if that helps.

Thank you for the help.

**Comment by firewallzer0** [comment] 2024-07-19 04:44
Having this same issue on Fedora 40 running KDE as the desktop environment. I either get an endless loop of captchas or a blank page.
![Screenshot_20240718_224300](https://github.com/user-attachments/assets/63bafb35-9230-4dd7-bae4-a0aa3233cf56)

I'll look into the the WEBKIT_DISABLE that you mentioned above and report back.

**Comment by openaudible** [comment] 2024-07-19 04:46
Let me know if running export WEBKIT_DISABLE_DMABUF_RENDERER=1 works.. I can disable it for all.. Shouldn't be needed. Thanks for the report.

**Comment by firewallzer0** [comment] 2024-07-19 04:56
Yeah running the export before launching allowed me to sign in.

**Comment by openaudible** [comment] 2024-07-19 05:00
I will create a beta with the flag set. Appreciate the report!

**Comment by corigne** [comment] 2024-07-19 12:51
> Let me know if running export WEBKIT_DISABLE_DMABUF_RENDERER=1 works.. I can disable it for all.. Shouldn't be needed. Thanks for the report.

After some digging, it appears webkit minibrowser is affected on some multi-gpu and NVIDIA systems. There were some PRs back in 2023 attempting to fix the issue, but they've struggled to nip it completely. I see 3 PRs claiming to attempt a fix. Disabling the DMA buffer renderer should be fine, as you said. That was the recommended workaround while they were troubleshooting.

https://bugs.webkit.org/show_bug.cgi?id=254807

**Comment by openaudible** [comment] 2024-07-31 03:03
Should be fixed in latest release 4.4.0 or higher.

**Closed by openaudible** 2024-07-31 03:03 UTC

**Comment by stratus-ss** [comment] 2024-11-24 15:55
I know this is closed but I ran into this issue on 4.4.3
[This answer](https://github.com/openaudible/openaudible/issues/1406#issuecomment-2238150884) allowed me to login again. Definitely not resolved from my perspective but the workaround is fine

**Comment by openaudible** [comment] 2024-11-24 15:59
We should set WEBKIT_DISABLE_DMABUF_RENDERER=1 in the app launch so it should always be set if you're using the latest release. 

If you are using the latest and still need to set that flag, let me know. I will double check we are setting it as well.

**Comment by stratus-ss** [comment] 2024-11-24 16:03
I see this is likely related to the distribution packaging. The desktop file doesn't have this option
https://aur.archlinux.org/cgit/aur.git/tree/openaudible.desktop?h=openaudible-bin

```
[Desktop Entry]
Type=Application
Name=OpenAudible
Comment=OpenAudible helps manage your Audible audiobooks
Exec=openaudible
StartupWMClass=install4j-org-openaudible-desktop-Application
Icon=openaudible
Categories=Utility;
X-Desktop-File-Install-Version=0.28
```

I'll file a bug with the maintainer. Thanks!

**Comment by openaudible** [comment] 2024-11-24 16:42
You can look at the Diagnostics from the about menu and see if it is set. 

Make sure you're using the latest 4.4.8 (currently). 

It shouldn't be needed as a startup argument.. as the install4j lets us set these for all versions.

**Comment by stratus-ss** [comment] 2024-11-24 17:28
Diagnostics show that it is present
```
"java": {
  "java.specification.version": "18",
  "java.runtime.version": "18.0.1+10",
  "java.class.path": "/opt/OpenAudible/.install4j/i4jruntime.jar:/opt/OpenAudible/.install4j/launcher27278ab6.jar:/opt/OpenAudible/./openaudible_gtk_x86_64.jar:/opt/OpenAudible/openaudible_gtk_x86_64.jar",
  "java.vm.vendor": "Eclipse Adoptium",
  "java.net.useSystemProxies": "true",
  "java.runtime.name": "OpenJDK Runtime Environment",
  "java.vendor.url": "https://adoptium.net/",
  "java.vm.specification.version": "18",
  "java.vm.name": "OpenJDK 64-Bit Server VM",
  "java.vendor.version": "Temurin-18.0.1+10",
  "sun.java.launcher": "SUN_STANDARD",
  "sun.java.command": "install4j.org.openaudible.desktop.Application",
  "java.vendor.url.bug": "https://github.com/adoptium/adoptium-support/issues",
  "java.io.tmpdir": "/tmp",
  "java.version": "18.0.1",
  "java.specification.vendor": "Oracle Corporation",
  "java.vm.specification.name": "Java Virtual Machine Specification",
  "java.version.date": "2022-04-19",
  "java.home": "/opt/OpenAudible/jre",
  "vm_args": [
   "-Dfile.encoding=UTF-8",
   "-Dsun.jnu.encoding=UTF-8",
   "-Doa_packaging=deb",
   "-DOARCH=",
   "-DWEBKIT_DISABLE_DMABUF_RENDERER=1"
  ],
  ```

**Comment by openaudible** [comment] 2024-11-24 17:32
That should be fine. Of course the other requirement is the WebKit 4.. but yes, looks correct. 

I looked at the link you sent and it looks like it needs to be updated with search release. I don't know how popular it is, but we could automate the links and checksum like we do for choco. We also have a script that can push to GitHub.

**Comment by stratus-ss** [comment] 2024-11-24 18:19
I'm happy to relay any comments you have for the maintainer so that you don't have to create an account just to comment.

As to the popularity, we don't really track that. The only "metric" on popularity is if someone goes to the webui and "votes" for the package. In the 2 decades I've been using linux, I have only done this a few times so I don't think it's at all reliable.

**Comment by openaudible** [comment] 2024-11-24 20:49
Ok. The later version has a new share directory that might make linking to images easier. 

Happy to write a script to help if I can. (Take a template and substitute version, url, checksum.) 

What is the command to install from that git page? 

Thanks

**Comment by stratus-ss** [comment] 2024-11-24 21:02
Under Arch based distros (Arch, manjero, SteamOS, Endeavour etc) there are AUR helpers that can be installed to do this for you such as 
* pacaur
* aurman
* pakku
* yay

However, the direct commands are as follows:
```
# download the package build info
git clone https://aur.archlinux.org/openaudible-bin.git

# change into the package directory
cd openaudible-bin

# make the package
makepkg -si --noconfirm
```
That should install the package for you. If you want to examine the package after it's built instead of installing it you would run
```
# noconfirm is optional
makepkg -s 
```
