### ISSUE TITLE
Java exception when exporting book list

### ISSUE THREAD

**Issue by derekgottlieb** [openaudible/openaudible#1255] opened 2023-08-28 12:50 UTC
When trying to export the book list for my library on OpenAudible 3.8.1 (MacOS), it's throwing a Java exception and the following is logged to the console log:

```
Aug 28, 2023 7:45:11 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Export_Book_List
Aug 28, 2023 7:45:11 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error
An error has occurred. Check File>Console for more details.
java.lang.Exception
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:41)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:914)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:848)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:363)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:73)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:576)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:133)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:146)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

```

**Comment by openaudible** [comment] 2023-08-28 15:02
That is a bug, and unfortunately, we generated a bad error message that doesn't show exactly where it happened.
A better error will be in the next release. What format were you exporting? json, xlsx, or csv?  
Make sure your disk is writable and the file isn't already open in another program. (pretty common to try to export to excel a second time and fail because the file is in use.)

**Comment by derekgottlieb** [comment] 2023-08-28 21:09
I'm clicking File -> Export Book List and it is immediately throwing the error. I'm not given the opportunity to select an output format, destination directory or filename for the export.

I was successful exporting to a csv in an older version, so the first thing I'd tried was deleting that old file. I also couldn't identify an app running with that file open.

**Comment by openaudible** [comment] 2023-08-28 21:15
That is odd. You can do a quick export by selecting all, copy, then paste into excel. (It won't  have all fields, just the fields in your table.) I'll post here when a new beta is ready to try.

**Comment by openaudible** [comment] 2023-09-04 18:40
We just posted a beta with better error logging. Hopefully. Feel free to try that and let us know. Thanks!
https://openaudible.org/beta

**Comment by derekgottlieb** [comment] 2023-09-04 19:55
Full console log from 3.8.1.1 beta:

```
Sep 04, 2023 2:51:28 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.8.1.1 for cocoa swt 4956 jvm 11.0.15
Sep 04, 2023 2:51:29 PM org.openaudible.Directories load
INFO: Loading directories. These must be online and read/writable:
->{
 "ZIP": "",
 "META": "/Users/derek/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "MP3": "",
 "PDF": "",
 "ART": "",
 "TMP": "/Users/derek/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "/Users/derek/Music/OpenAudible"
}
Sep 04, 2023 2:51:29 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/derek/Library/OpenAudible/settings.json exists=true size=577
Sep 04, 2023 2:51:29 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1637724639508
Sep 04, 2023 2:51:29 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Sep 04, 2023 2:51:29 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.8.1.1 mac
Sep 04, 2023 2:51:30 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Sep 04, 2023 2:51:31 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: sw_vers -productVersion 
Sep 04, 2023 2:51:31 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: uname -m 
Sep 04, 2023 2:51:31 PM org.openaudible.util.Arch systemArch
INFO: Ran systemArch: x86_64
Sep 04, 2023 2:51:31 PM org.openaudible.util.Arch macVenturaOnIntel
INFO: MacOS Ventura on Intel: 10.15.7 x86_64 is: false
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.manager.views.SummaryPanel <init>
SEVERE: Created swt summary panel.
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.manager.views.BookTable layoutColumns
INFO: table col0 widths: 14,14,14,25,14, zoom=100
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.manager.views.BookTable layoutColumns
INFO: table col0 widths: 14,14,14,14,14, zoom=100
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.prefs.WindowPrefs validBounds
WARNING: Window position Rectangle {45, 34, 942, 1045} is not within screen area: Rectangle {50, 50, 1820, 980}
Sep 04, 2023 2:51:31 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/derek/Library/OpenAudible/settings.json exists=true size=577
Sep 04, 2023 2:51:31 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1637724639508
Sep 04, 2023 2:51:31 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.manager.AudibleGUI loadPrefs
INFO: Saving prefs on startup, reason: setting lastVersion,
Sep 04, 2023 2:51:31 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 579 to disk:/Users/derek/Library/OpenAudible/settings.json
Sep 04, 2023 2:51:31 PM org.openaudible.desktop.swt.prefs.WindowPrefs validBounds
WARNING: Window position Rectangle {45, 34, 1393, 693} is not within screen area: Rectangle {50, 50, 1820, 980}
Sep 04, 2023 2:51:31 PM org.openaudible.library.LibraryManager activate
INFO: activating: /Users/derek/Music/OpenAudible [
 {
  "path": "/Users/derek/Music/OpenAudible",
  "kind": "BASE",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/derek/Music/OpenAudible/books",
  "kind": "BOOKS",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/derek/Music/OpenAudible/web",
  "kind": "WEB",
  "exists": false,
  "enabled": true
 },
 {
  "path": "/Users/derek/Library/OpenAudible",
  "kind": "META",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/derek/Library/OpenAudible/tmp",
  "kind": "TMP",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Applications/OpenAudible.app/Contents/Resources/app",
  "kind": "APP",
  "exists": true,
  "enabled": true
 }
]
Sep 04, 2023 2:51:31 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1) Refreshed file cache:1169 why force update active=false took 251 ms. to complete.
Sep 04, 2023 2:51:31 PM org.openaudible.library.BookLibrary load
INFO: Loading /Users/derek/Music/OpenAudible/books.json
Sep 04, 2023 2:51:33 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Sep 04, 2023 2:51:34 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 2) Refreshed file cache:1169 why force update active=false took 97 ms. to complete.
Sep 04, 2023 2:51:35 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 3) Refreshed file cache:1169 why booksUpdated active=false took 70 ms. to complete.
Sep 04, 2023 2:51:36 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Sep 04, 2023 2:51:36 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Sep 04, 2023 2:51:36 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 4933 ms. to complete.
Sep 04, 2023 2:51:39 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: sysctl -n sysctl.proc_translated 
Sep 04, 2023 2:51:39 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Sep 04, 2023 2:51:45 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Export_Book_List
Sep 04, 2023 2:51:45 PM org.openaudible.desktop.swt.manager.ImportExport exportBookListGUI
SEVERE: error exporting books
java.lang.NullPointerException
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:377)
	at org.openaudible.desktop.swt.gui.ChooseFile.saveAs(ChooseFile.java:119)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:991)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:977)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:363)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:73)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:637)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:133)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:146)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Sep 04, 2023 2:51:45 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: ERROR
Unexpected error exporting books
3.8.1.1beta
java.lang.NullPointerException
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:377)
	at org.openaudible.desktop.swt.gui.ChooseFile.saveAs(ChooseFile.java:119)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:991)
	at org.openaudible.desktop.swt.manager.ImportExport.exportBookListGUI(ImportExport.java:977)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:363)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:73)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:637)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:133)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:146)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Sep 04, 2023 2:51:50 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:ERROR body:Unexpected error exporting books
java.lang.NullPointerException response:BUTTON_OK
Sep 04, 2023 2:51:55 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment] 2023-09-04 20:51
Thank you for the report. That nailed down the line number. Looks like it is in a library only used by intel Mac. (as opposed to simply being in our code.) Will investigate!

**Comment by openaudible** [comment] 2023-09-05 15:03
OK, I upgraded the widget library (SWT) to the latest. Can you give beta 2 a try? I am unable to reproduce as I think it requires an Intel Mac and an older OS.

**Comment by derekgottlieb** [comment] 2023-09-05 16:17
With beta 2, the file save dialog window successfully opened and I was able to export my book list to csv. Looks like that fixed it. Thanks!

**Comment by openaudible** [comment] 2023-09-05 21:19
Awesome. Thanks for the feedback! Will get a final release out soon. (Lots of new features for more complex audiobook libraries in the works…)

**Comment by openaudible** [comment] 2023-09-27 17:56
Posted the final version, and a new beta is also out if you're looking for the cutting edge.
https://openaudible.org/beta

**Closed by openaudible** 2023-09-27 17:56 UTC
