### ISSUE TITLE
no automatic converting?

### ISSUE THREAD

**Issue by Amazondoc** [openaudible/openaudible#345] opened 2020-05-05 18:17 UTC
Since I have your attention --

Many versions ago, I was able to automatically convert files. That is, once OpenAudible imported the aax files, conversion to mp3 started automatically, without me having to take any further action. But that stopped working. These days I have to convert the files, then manually highlight them and select "convert to mp3". 

Yes, I do have the "automatically convert to mp3" option checked in preferences. That doesn't seem to make any difference.

Please advise.

**Comment by openaudible** [comment] 2020-05-05 21:02
It should be working. See if you can find the word checkAutomation in the console (CTRL-E) and it should say what it is supposed to do....  Then its supposed to do it. If you see any errors, that might be the cause.

**Comment by Amazondoc** [comment] 2020-05-05 21:14
It's a Mac -- so it's command-E, not ctrl-E . ;-)

I couldn't find "checkAutomation". I imported 16 books at the same time, then had to manually select them all for conversion (as I've had to do for months). Here's just the part where the import process is finishing and the conversion process is starting -- you'll see it doesn't even appear to check for an automated conversion command:

INFO: Running: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -i "/Users/Ione/Files/audiobooks/f -- Hutchinson, C -- Audible Originals -- Proof of Love.aax" -f ffmetadata - 
May 05, 2020 1:11:52 PM org.openaudible.desktop.swt.manager.ImportExport _importFile
INFO: Copying file /Users/Ione/Files/audiobooks/f -- Hutchinson, C -- Audible Originals -- Proof of Love.aax to /Users/Ione/Files/audiobooks/OpenAudible/aax/f -- Hutchinson, C -- Audible Originals -- Proof of Love.AAX
May 05, 2020 1:11:52 PM org.openaudible.desktop.swt.manager.ImportExport _importFile
INFO: Imported f -- Hutchinson, C -- Audible Originals -- Proof of Love.aax -> Proof of Love
May 05, 2020 1:11:52 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 40111 to disk:/Users/Ione/Library/OpenAudible/tmp/saved_books.json
May 05, 2020 1:11:52 PM org.openaudible.Audible save
INFO: Save books took 14 ms. to complete.
May 05, 2020 1:14:22 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
May 05, 2020 1:14:22 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Locked Together In progress:3 queue: 13 threads:

**Comment by openaudible** [comment] 2020-05-06 04:02
Ah- Auto-convert only works when you download a book. I suppose I could add it to when you import one. Will do for next release.

**Comment by Amazondoc** [comment] 2020-05-06 15:28
Huh. I've never downloaded books directly into OpenAudible, and Auto Convert used to work. So I guess you changed that feature several versions ago?

**Comment by openaudible** [comment] 2020-05-06 17:19
Not sure. Import AAX is done by the File: Import Files... where you select AAX files already downloaded (by audible download manager).. Downloading is done when OA scans your books and you select "Download".. Most use our downloader.. but its possible things have changed. I added a check at the end of the import to see if you want to automate conversions. That'll be in the next version... Date TBD.

**Comment by Amazondoc** [comment] 2020-05-06 17:30
Yeah, I know how the downloading is done, but I've never used it. For me, OpenAudible doesn't play well directly with the Audible website (for instance, I just tried the command-K "connect with Audible" command, and it disconnected after about 10 seconds), and since I download all my Audible books anyway, I've never bothered to figure out what was going on there. I have a very large Audible library (currently about 1900 books), and I suspect it's gagging on the large library size.

So anyway -- I know OpenAudible originally did the AutoConvert on imported books, because that's how I've always used it. But it stopped doing that quite a few versions ago. If you're putting it back in, that's great -- it will be very convenient! So, thanks in advance!

**Comment by openaudible** [comment] 2020-05-09 00:12
OK. Check it out in 2.0.6. Should be fixed.

**Closed by openaudible** 2020-05-09 00:12 UTC

**Comment by Amazondoc** [comment] 2020-05-09 04:32
Ooooo, you got my hopes up only to dash them. Nope, I still had to do it manually. But thanks for trying!
