### ISSUE TITLE
Chapter does not start at correct time

### ISSUE THREAD

**Issue by ParitoshVaidya** [openaudible/openaudible#274] opened 2020-02-23 06:42 UTC
There is an issue with the chapter number and the time at which it starts. It is not matching at all.

**Update 1**: As per @paolofulgoni 's comment, I tested the file on various audiobook players. All got this issue. I used inAudible for conversion, and chapters matched correctly.

**Comment by paolofulgoni** [comment] 2020-02-23 14:06
I had the same issue.
I wonder if it's because the player has some trouble with the variable bitrate.
I tried to set a constant bitrate (see https://trac.ffmpeg.org/wiki/Encode/MP3) but I was not able to run the latest version of the software...

**Comment by openaudible** [comment] 2020-02-24 21:27
We get the chapter times from ffprobe. We then split the book using ffmpeg. All commands to ffprobe and ffmpeg are printed to the log window. If you wanted, you could copy and paste the commands to the terminal to accomplish the same thing or attempt changes. 

What OS are you using?

Are all books bad, or just some?


What book is having problems?  If you open chapter 2, how many seconds is it off by, approximately? If you play chapter 10, is it off by 10x more?

The error could be bad chapter data in the aax.. or it could be that ffmpeg is having a hard time finding the exact times, due to variable bitrates. It can also depend on what version of ffmpeg you're using and which platform. 

I've converted many dozens of files and haven't been able to reproduce.  So the only way I can propose a fix is to know how to reproduce it.. Also, if you have multiple operating systems, does the bug affect Mac Linux and Windows or just one?

**Comment by openaudible** [comment] 2020-03-04 22:49
Closing from lack of replies and not reproduced.

**Closed by openaudible** 2020-03-04 22:49 UTC

**Comment by paolofulgoni** [comment] 2020-03-05 21:35
Sorry for the late answer.

I'm using Windows 10.
I have tried only a few books and they all have wrong chapters.
I tried many audiobook players on Android, they all have some issue.

I downloaded the latest version of ffmpeg and tried the same commands from the log, got the same issue.
Then I tied to use constant bitrate, same issue.

It doesn't seem an issue of openaudible anyway.
