### ISSUE TITLE
Followup to previous issues about new audio books missing purchase date 

### ISSUE THREAD

**Issue by matthewb1999** [openaudible/openaudible#426] opened 2020-08-06 11:32 UTC
Hi,

A few weeks ago I raised an issue were no audiobook I have purchased since April has a purchase date.

I did try your suggestion of logging into my account from the open audible browser and then refreshing the book info on thee books with missing information but it still missing the purchase date.

I did also try reinstalling the program

![image](https://user-images.githubusercontent.com/62423430/89527133-c1113d00-d7e0-11ea-9d07-3e6843dbd3b9.png)

Is there a step that I missed?

Any help with this would be appreciated.

Regards,

Matthew.

**Comment by flipside786** [comment] 2020-08-10 15:01
I can verify i am having the same issue with two recent audible books i have added.

**Comment by benjaminewton** [comment] 2020-08-17 15:03
I also am having that issue. It appears some books bought in the last two months have dates, but most do not. 

I have imported a book bought via audible.com and this does have a purchase date.

**Comment by moocower** [comment] 2020-08-19 20:25
Same issue here as well. Everything in the last couple months or so have no purchase dates.

**Comment by siditm** [comment] 2020-08-20 17:25
This has been a problem for me even on v 1.x.x. Was missing all dates for books both in last couple of months.
I was on v 2.1.3 and the newest quick sync did populate purchase dates for my latest acquisition. Did update to 2.3.3, deleted the whole library and after full sync none of the dates are showing.
I'm on Win 7 and using Audible UK, I can see webpage window going through book webpages during sync. I'm guessing regex used for parsing isn't full proof :(
I've used "view sourece" and diffchecker to compare webpages for one new book that showed the date and one that didn't, no obvious differences there.

**Comment by openaudible** [comment] 2020-08-21 03:47
The audible "library" view no longer shows the purchase date in the library. 
https://www.audible.com/library/titles
So the date has to be parsed by doing a "Get Info", which we do once.. but you can do manually by selecting one or more books and doing a "Refresh Info" from the Action Menu.

**Comment by siditm** [comment] 2020-08-21 05:05
> but you can do manually by selecting one or more books and doing a "Refresh Info" from the Action Menu.
Already tried this, no effect; still missing _Purchase Date_.

**Comment by openaudible** [comment] 2020-08-25 00:36
Checking that out. Looks like a bug. Maybe just for the UK? Not sure. Trying to reproduce and fix.

**Comment by Butterfly-Dragon** [comment] 2020-08-25 15:31
I currently have 59 books without a purchase date... trying to see what happens with a "refresh info"...

Nope.

Listen: you are straight up accessing my account with your program.

You can totally go to my purchase history to see what i have bought and when and if some stuff is missing or something. 😅

In fact you can also use that to check my borrows/gifts/preorders too so i can see what stuff i own and when it will be released.

**Comment by matthewb1999** [comment] 2020-08-25 18:22
If its an issue for the UK, I will try using a VPN to see if that changes anything out curiosity open audible what county are you in?

**Comment by Butterfly-Dragon** [comment] 2020-08-25 18:40
i'm using audible.com

**Comment by openaudible** [comment] 2020-08-25 23:55
OK. Audible keeps changing how to display the date purchased. A lot of my books have no date purchased information at all. I will keep working on this. It used to be part of the library view, but for some reason it was removed (although you can still sort by date purchased.. just can't see what that is.) 

Hang tight..

**Comment by Butterfly-Dragon** [comment] 2020-08-26 00:07
right now the only place where i see any date is on my purchase history page. Everywhere else  there is just a vague "you have it" Fun fact... the purchase history page also has some data and icons for books which do not exist anymore but that are still part of my library. (the same data and the same icons are also in the library)

**Comment by siditm** [comment] 2020-08-26 06:45
> (although you can still sort by date purchased.. just can't see what that is.)
> 
Not really, clicking _Purchase Date_ does nothing, meaning the list is sorted by _Title_ A-Z (default sorting order on app runtime).

**Comment by Butterfly-Dragon** [comment] 2020-08-26 06:54
> > (although you can still sort by date purchased.. just can't see what that is.)
> 
> Not really, clicking _Purchase Date_ does nothing, meaning the list is still sorted by _Title_ A-Z (default sorting order on app runtime).
> 
> EDIT:
> It actually sorts the list by _Title_ A-Z.

**Comment by siditm** [comment] 2020-08-26 06:58
> > Not really, clicking _Purchase Date_ does nothing, meaning the list is still sorted by _Title_ A-Z (default sorting order on app runtime).
> 
> he means the Audible Library on the Audible site.

Ok, but for me _Date Added_ is default sorting order on https://www.audible.co.uk/library/

**Comment by Butterfly-Dragon** [comment] 2020-08-26 07:19
It... does not work like that. Because... it already works like that. It already goes through the library and checks book by book what goes where and the extra data and stuff.

Purchase date is not there any more.

**Comment by siditm** [comment] 2020-08-26 09:30
> It... does not work like that. Because... it already works like that. It already goes through the library and checks book by book what goes where and the extra data and stuff.
> 
> Purchase date is not there any more.

Well it is there (on each book's page) at least in case of my UK account [https://imgur.com/a/GpvrYSU](url), just like the html code that I've posted earlier.

**Comment by Butterfly-Dragon** [comment] 2020-08-26 09:48
![image](https://user-images.githubusercontent.com/33538906/91288940-e535bd80-e791-11ea-91fa-21e7ad4583d0.png)
yeah, not anymore in the US version. And if i clock on "more options" i get this:
![image](https://user-images.githubusercontent.com/33538906/91289026-05657c80-e792-11ea-9f70-de881d0f6cd6.png)

**Comment by siditm** [comment] 2020-08-26 10:32
> ![image](https://user-images.githubusercontent.com/33538906/91288940-e535bd80-e791-11ea-91fa-21e7ad4583d0.png)
> yeah, not anymore in the US version. And if i clock on "more options" i get this:
> ![image](https://user-images.githubusercontent.com/33538906/91289026-05657c80-e792-11ea-9f70-de881d0f6cd6.png)

Ok, now this makes more sens. How about https://www.audible.*/account/purchase-history ?
Mine still shows _Purchased_ date:
![Untitled](https://user-images.githubusercontent.com/20173471/91293356-2c26b180-e798-11ea-9352-e553faa04807.png)

**Comment by Butterfly-Dragon** [comment] 2020-08-26 11:07
i have been saying it since my first reply
https://github.com/openaudible/openaudible/issues/426#issuecomment-680098885

**Comment by openaudible** [comment] 2020-08-26 17:03
Yeah, purchase date has disappeared for me.

Looking at the purchase history page. I'd prefer to stay out of people's "account" settings. 

The page is OK, but would require a bit of a kludge because the software would have to go through each year separately. Also, the date is buried in html code and not available as easily parsed data. 

Thanks for the feedback.. 

I have a few other things to try as well..

**Comment by Butterfly-Dragon** [comment] 2020-09-29 14:59
can confirm that in the library page as of today the ability to sort by purchase date is gone. 😓

**Comment by siditm** [comment] 2020-09-29 18:03
In the meantime how about adding an integer column (n, n-1, ..., 2, 1) to let us sort by purchased order, after all default sorting order for _/library_ is **Date Added**.

**Comment by Butterfly-Dragon** [comment] 2020-10-11 16:43
i do not have a "purchase date" anymore i have a "date added" sooo it shows when it got added to the library, i cannot see (for example) when i bought a prepurchase.

![image](https://user-images.githubusercontent.com/33538906/95684388-aba9fc00-0bf1-11eb-9d9e-fd1864d03876.png)

**Comment by kai-uwe-rommel** [comment] 2020-10-11 17:16
Probably depends on localization. In the german version, it says "Kaufdatum", e.g. "purchase date" ...

**Comment by matthewb1999** [comment] 2020-10-16 12:10
Hi Everyone, 

I just wanted to say I updated to the latest version 2.3.5 and after refreshing info on books that did not have a purchase date I now have a purchase date which is FANTASTIC!

**Comment by Butterfly-Dragon** [comment] 2020-10-16 13:11
i can confirm that not being the case for me  😓 
![image](https://user-images.githubusercontent.com/33538906/96262236-d1544e00-0fc1-11eb-9632-5abc40026a5a.png)

**Comment by siditm** [comment] 2020-10-16 13:24
> Hi Everyone,
> 
> I just wanted to say I updated to the latest version 2.3.5 and after refreshing info on books that did not have a purchase date I now have a purchase date which is FANTASTIC!

Yes "Refresh Info" did the trick for my UK lib, thanks for the tip @matthewb1999 and thank you @openaudible for fixing this.
Here's hoping Audible won't break it again too soon.

**Comment by siditm** [comment] 2020-10-21 18:40
A new bug seems to have manifested itself :(
Inconsistent date format between Purchased Date in book list its YYYY-DD-MM while when shown in book info it's DD-MM-YY. Because of YYYY-DD-MM date format sorting by this column doesn't work as expected.
Release dates have correct format YYYY-MM-DD, purchase date should use the same date format.

It's not yet December ;)

![inconsistent date format](https://user-images.githubusercontent.com/20173471/96767645-17a01780-13dd-11eb-8248-f452d0bf64ad.png)

**Comment by haumacher** [comment] 2020-10-29 18:34
Having updated to version 2.3.5, did a full refresh with Ctrl+A + F5 but still no purchase date in the list. Using the German version of audible:

![image](https://user-images.githubusercontent.com/5607145/97616810-52c5ca80-1a1d-11eb-83b4-59cbe92b2080.png)

**Comment by siditm** [comment] 2020-10-30 14:29
> Having updated to version 2.3.5, did a full refresh with Ctrl+A + F5 but still no purchase date in the list. Using the German version of audible:
> 
> ![image](https://user-images.githubusercontent.com/5607145/97616810-52c5ca80-1a1d-11eb-83b4-59cbe92b2080.png)

Not sure if it's necessary but as usual I've started by selecting **Controls > Connect to Audible (Ctrl+K).**
I'm guessing you've also tried to refresh book info for this particular book with **right-click > Refresh Info**.

Currently the only books in my library without Purchase Date are as expected returned or no longer available ones, unfortunately the dates have a incorrect format as mentioned above.

**Comment by haumacher** [comment] 2020-10-31 08:13
Yes, I also tried a refersh from the context menu. The one without a date is a newly purchased one.

**Comment by openaudible** [comment] 2020-11-05 16:10
Closing this. We do our best to grab it, but some versions of the audible web site don't show the purchase date on the library list or in the book information page(s). Thanks everyone for the feedback.

**Closed by openaudible** 2020-11-05 16:10 UTC

**Comment by haumacher** [comment] 2020-11-05 20:23
> ...but some versions of the audible web site don't show the purchase date on the library list or in the book information page(s).

Didn't you see the marked date in the page on my screenshot? It is there but nor grabbed...

**Comment by siditm** [comment] 2020-11-05 21:21
> A new bug seems to have manifested itself :(
> Inconsistent date format between Purchase Date in book list its YYYY-DD-MM while when shown in book info it's DD-MM-YY. Because of YYYY-DD-MM date format sorting by this column doesn't work as expected.
> Release dates have correct format YYYY-MM-DD, purchase date should use the same date format.
> 
> It's not yet December ;)
> 
> ![inconsistent date format](https://user-images.githubusercontent.com/20173471/96767645-17a01780-13dd-11eb-8248-f452d0bf64ad.png)
What about making sure grabbed values are in uniform date format so they can actually be used for sorting.
