### ISSUE TITLE
dark theme detection

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#816] opened 2022-01-01 13:37 UTC
Despite my system using dark theme if i set the color scheme of openaudible to "system" it only uses light theme.

I have confirmed that if i use light or dark theme it only uses the light one with the "system" option.

**Comment by openaudible** [comment] 2022-01-01 21:58
Which operating system? 

From: https://javadoc.scijava.org/Eclipse/org/eclipse/swt/widgets/Display.html#isSystemDarkTheme()
Note: This operation is a hint and is not supported on platforms that do not have this concept.

Note: Windows 10 onwards users can separately configure the theme for OS and Application level and this can be read from the Windows registry. Since the application needs to honor the application level theme, this API reads the Application level theme setting.

**Comment by Butterfly-Dragon** [comment] 2022-01-01 22:05
Microsoft Windows [Version 10.0.19044.1415]

**Comment by openaudible** [comment] 2022-01-02 06:03
Confirmed.. 
Yeah, we detect that the mode is set to dark. But with the mode set to system, we don't explicity set any foreground or background color.. the system is supposed to do it and use the dark background. Not sure whats up but will dig into a little.

**Comment by openaudible** [comment] 2022-01-09 19:31
No idea why that is. Closing as "won't fix". Not my code... just set mode to dark.

**Closed by openaudible** 2022-01-09 19:31 UTC

**Comment by Butterfly-Dragon** [comment] 2022-01-09 19:40
ok
