### ISSUE TITLE
Full sync fails with podcasts enabled in library

### ISSUE THREAD

**Issue by Kalthax** [openaudible/openaudible#1449] opened 2024-08-20 01:03 UTC
v4.4.4 - When podcasts are enabled, full sync fails. It freezes during or just after the podcast scan.

Error: An unexpected bug has been detected!
We may need more information from you to help debug this. Check the File > Log Window for more details.
Feel free to contact us if want us to assist.
Deadlock detected after cancel Deadlocked Threads! id=242 name=Audible Library Scan state=BLOCKED
lockName=org.openaudible.bookfiles.BookFiles@65b66b08 lockOwnerName=Thread-162 id=588 name=Thread-162 state=BLOCKED lockName=java.util.HashMap@4726927c
lockOwnerName=Audible Library Scan

I can send over the diagnostic logs, but I don't want them to be public.

With podcasts off, full sync works. Quick sync works either way.

**Comment by openaudible** [comment] 2024-08-20 15:26
That's a bug for sure... That is a good catch -- haven't seen that yet. 

I'd love to see the logs. Please send to info at openaudible dot org or send through our web form. I'll try to reproduce on my end as well.

**Comment by Kalthax** [comment] 2024-08-20 16:03
OK. I emailed over the logs. If you need anything else, let me know.

**Comment by openaudible** [comment] 2024-08-20 23:28
Thank you. Deadlocks are a pain to debug. I will build a new version that will have some checks for preventing that bad behavior. Appreciate the email!

**Comment by gateslee2210** [comment] 2024-08-27 21:13
I am having the same problem. Audiobooks - check; podcasts - hang. Any progress on a new version?

**Comment by openaudible** [comment] 2024-08-28 00:24
I posted a new beta at https://openaudible.org/beta
It has some changes that might help.
You can now turn on/off meta updates, podcasts and annotations in the Manage Libraries dialog.
If you can run a rescan with the File: Log Window showing, if it hangs, perhaps take a screenshot and send it to us (info at openaudible dot org.)
Thanks for help with this-- haven't been able to reproduce.

**Comment by gateslee2210** [comment] 2024-08-28 01:02
Thank you. I'll give it a try tomorrow.

**Comment by Kalthax** [comment] 2024-08-28 02:55
OK, using the latest beta, a full library sync with podcasts, metadata, and annotations works, sort of. No crashes, no hangs, no freezes. It correctly sees all of the podcasts I am subscribed to, and it creates a folder for each podcast in the expected location. However, it doesn't download ANY podcast files, it doesn't even appear to try to do so.

My podcast library isn't enormous, but my book library is. I tried this same account with Libation which also has podcast support and Libation properly downloads all podcast files. I know the programs aren't the same, but I wanted to see if there was something about my library that makes it hard to fetch podcasts. Since it worked, it doesn't seem to be an issue specifically with my account.

We're definitely making progress, though. I look forward to enjoying my podcasts in OpenAudible.

**Comment by openaudible** [comment] 2024-08-28 04:00
Good to hear.
At this time, I think you need to click on the blue "podcasts" in the library or select it from the search dropdown... then the episodes will be shown.. From there you can select one or more to download/convert.
We didn't enable automatic download in case there are 5000 episodes. Not sure the best solution if you have subscribed to a podcast. (These show up with a blue hard to see microphone icon in the books table.)

**Comment by Kalthax** [comment] 2024-08-28 05:06
When you select a podcast, there is no way to download or convert anything. Those options are greyed out from the contextual menu and regular menu. If you go to the files info screen, it refers to the folder it created, there is no way to download episodes, there either. I don't mind having to tell it to download the episodes, but I can't figure out how to do that.

Also, I would think telling people somehow when they enable podcasts how to get OA to download the files would be useful, because as it stands that behavior is not like the way other file types are handled. Anything enabled is automatically downloaded.

**Comment by gateslee2210** [comment] 2024-08-28 13:57
The beta **definitely** helped. Like Kalthax,, I can now see my Podcasts. Podcast titles are not downloadable, but individual episodes are. However the episodes are not connected with a given Podcast title, so its all kind of a jumble. Am I missing something here? And thanks for the quick turnaround on the beta.

**Comment by gateslee2210** [comment] 2024-08-28 14:17
Like Kalthax said:
"I don't mind having to tell it to download the episodes, but I can't figure out how to do that."

**Comment by openaudible** [comment] 2024-08-28 17:54
Ok.. Found the bug with our podcasts. Try the latest beta. 
We try to keep new features "on request" until we work out the bugs.. 
Hopefully this version will work better for you.
https://openaudible.org/beta

**Comment by gateslee2210** [comment] 2024-08-28 18:25
The 4.4.4.2 beta installs and initializes just fine. But when I do **Controls --> Full Audible Library Sync**, I get an error: "Error Refreshing Library. No active accounts." Tried logging out and logging back in etc. to no avail. Went back to 4.4.4.1 beta, which does not have this problem.

**Comment by gateslee2210** [comment] 2024-08-28 18:30
BTW, the Summary pane says: "You are connected to audible. You can do a 'Full Library Sync' or 'Quick Library Sync' from the Controls menu."

**Comment by openaudible** [comment] 2024-08-28 18:54
Oh shoot. Working on assigning zero, all, or one account to each library. For a temp fix, go to Manage Libraries and under Accounts: Set your primary account. Building a 4.4.4.3 which will be https://openaudible.org/beta shortly.

**Comment by gateslee2210** [comment] 2024-08-28 19:12
That worked to get 4.4.4.2 running. Getting there. Still not picking up available episodes for a given Podcast, so there is nothing to download.

**Comment by openaudible** [comment] 2024-08-28 19:18
You will need to do a Full Audible Sync from the Control Menu. The quick rescan only checks for books since your last purchase.

**Comment by Kalthax** [comment] 2024-08-28 19:19
OK 4.4.4.3 works. It automatically downloads all podcast files very quickly. It was also able to play podcast episodes just fine.

**Comment by Kalthax** [comment] 2024-08-28 19:27
OK, just to clarify one thing, it looks like it downloaded the first 20 episodes if there were that many, but it didn't go any further, and I don't seem to have all of the undownloaded episodes in OA, so I can't tell it to get more. How should I do that?

**Comment by gateslee2210** [comment] 2024-08-28 19:51
Yup. 4.4.4.3 working! Trying to make sense of it all using the sorting tools for the table.

**Comment by openaudible** [comment] 2024-08-28 19:52
Fixing. Little worried about adding 500+ podcasts.. but memory is cheap, I guess....

**Comment by Kalthax** [comment] 2024-08-28 20:02
Maybe a preference option to download the last "X" podcast episodes as well as the most current? Set that to a low default and this way OA won't crash instantly if someone has thousands of episodes? Then you could work on a separate window for podcasts in a future version?

**Comment by Kalthax** [comment] 2024-08-28 20:03
Doing that would also allow the user just to nuke or edit the preference file to get things working again if they set it too high for their machine.

**Comment by gateslee2210** [comment] 2024-08-29 00:25
@openaudible Just a quick thank you for solving the problem as quickly as you did. Very much appreciated!

**Comment by Kalthax** [comment] 2024-08-30 14:33
Oh, I saw the new beta 4.4.4.4 this morning. I tried it. It correctly saw all of my podcast episodes and added them to the list, but it didn't download them automatically, which is OK. Now I can download the episodes I want to keep. Thanks for working on this!

**Comment by Kalthax** [comment] 2024-08-30 14:44
Looks like I spoke a little too soon. The podcasts that were downloaded earlier are fine, but all of the podcast episodes in the list that haven't been downloaded yet give this error:

**Comment by openaudible** [comment] 2024-08-30 17:57
Try 4.4.4.5.. https://openaudible.org/beta

**Comment by Kalthax** [comment] 2024-08-30 18:10
OK, same issue, same error even after a full sync. I tried several episodes from different podcasts.

Let me know if there's something else you want me to try.

**Comment by Kalthax** [comment] 2024-08-31 20:33
.6 has the same problem, though I don't know if that build was meant to fix this issue.

**Comment by openaudible** [comment] 2024-08-31 21:05
Hmm. That is weird.. can you send a bug report from the about menu. Use this issue number. Maybe double check you're not out of disk space?

**Comment by Kalthax** [comment] 2024-08-31 21:34
Sent as requested. Over 2 TB on every volume that is involved in some way with OA.

**Comment by openaudible** [comment] 2024-09-12 14:09
Should be fixed in final version.

**Comment by Kalthax** [comment] 2024-09-12 14:58
The version that is on the website now 4.4.5 or a new version that will be available shortly? In 4.4.5 non-beta, even after doing a full sync, trying to download a podcast episode that's not currently stored locally fails with the same error above. Does your fix only apply to new libraries?

**Comment by openaudible** [comment] 2024-09-12 15:06
Well, I had hoped it was fixed. Podcasts need to be in the podcasts/podcast_name/podcast_episode.m4b (or mp3) format.
If they were added earlier and don't show up correctly, it is possible you need to delete them and try to re-download them.
Try a Controls: Full Audible Library Sync and click on the library status "Podcasts"... from there you're supposed to be able to see them all and download them individually, assuming they are associated with your account and your account is "connected".

If that doesn't work, please send one more bug report. Turn off preferences auto-download. Quit and open OpenAudible. Full Rescan. Select one podcast and Action: download. If you get an error, see if the error makes sense.. otherwise, send another bug report... issue 1449.

**Comment by Kalthax** [comment] 2024-09-12 15:54
Yeah, that didn't help. I sent off the bug report with more detail about the specific things I tried. Thanks for looking into this.

**Comment by openaudible** [comment] 2024-09-13 00:44
Got your bug report. It looks like a lot of old (expired) items that are no longer in your library.
There were a number of periodicals. We typically filter those out, since those include things like the new york times.. but in your case it looked like some non-standard stuff.. so those can be downloaded in the latest beta if you check the new box "Enable Periodicals" in the File: Library Settings dialog. 
But the red items will need to be "re-added" (if possible) to your audible library, if they are still available. And or deleted. 
https://openaudible.org/beta

**Comment by Kalthax** [comment] 2024-09-13 01:01
Thanks. I’ll give it a try shortly, but I don’t know if you looked at the item I actually tried downloading. It was a podcast that is active and still adding episodes and the episode I tried downloading is still available and I can download it via Audible’s app or via libation. I’ll let you know how the new beta works tonight. Thanks!

**Comment by openaudible** [comment] 2024-09-13 01:53
I didn't see any active podcasts in your library. Make sure it shows in your library. You can let me know the name of the podcast here or by email (info at OpenAudible dot org)

**Comment by openaudible** [comment] 2024-09-13 17:12
Ah- found them-- the bug report had a bug.. lol.

Made some changes based on your report that should help.
Make sure Podcasts are enabled (should be) and do a controls full audible sync...
then click the podcasts in thelibrary status. On the table, you can right-click to set the table to show series name.
Find those you want to download and they should now work.

Beta 4.4.5.2:

https://openaudible.org/beta

**Comment by Kalthax** [comment] 2024-09-13 18:44
4.4.5.2 works great for podcasts. It downloaded absolutely everything quickly and without any errors. I didn't even have to do a full resync. I did try enabling periodicals and then doing another full resync, but I don't think my account has anything that qualifies. The NYT/WSJ downloads were discontinued and removed unless you actually paid for a subscription. So I can't say if the Periodicals feature works as desired. Sorry.

However, as this specific bug request goes, I consider it completed now. Thanks so much for working so hard on this.

**Comment by openaudible** [comment] 2024-09-13 20:11
Great news. Thank you very much for your help.

**Closed by openaudible** 2024-09-13 20:11 UTC
