### ISSUE TITLE
Conversion got non-zero response:3

### ISSUE THREAD

**Issue by benjaminewton** [openaudible/openaudible#250] opened 2019-12-28 20:38 UTC
I have converted and chapter split a number of audiobooks without issue, until this one (American Gods: The Tenth Anniversary Edition) which starts converting but ends up with the State: "Conversion got non-zero response:3".

I have tried deleting the AAX file and downloading it again and converting it again but I get the same outcome.

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/59257272/71549222-b0c6f300-29b1-11ea-9d78-3f37b6c85b5f.png)

**Comment by M1DLG** [comment] 2019-12-29 15:46
I have the same issue, out of more than 1700 aax files 9 fail to convert. I was successful using Epubor. I suspect the DRM or part of the encoding is different to the others.

**Comment by parkylondon** [comment] 2019-12-30 21:34
I just started using OpenAudible this past couple of days and hit this issue earlier today. I cannot see any connection with the dozen or so books I have remaining from my conversion task - they aren't the most recent / oldest of my Audible files, neither are they the biggest or the smallest. 

I had a look at the source for the application and although I can see the reference to the "Conversion got non-zero response" there seems to be no look up for the error codes. 

I'd just like to know why they are failing! I've done 180 books successfully and it's just this 11 files left.

FWIW, I'm doing it so they can go on an SD card for my older car - it has a 30 pin iPhone cable but I don't have a 30pin device any more!

**Comment by parkylondon** [comment] 2019-12-31 09:49
FWIW, one of mine refusing to convert is also American Gods, per the above post...
![Screenshot 2019-12-31 09 48 46](https://user-images.githubusercontent.com/59375450/71617423-e4bd3680-2bb2-11ea-9d3f-54230dda2c1b.png)

**Comment by Bhlowe** [comment] 2019-12-31 15:48
If it happens part way through encoding, it isn’t a podcast/escape unsupported format. 

If I were to look for a solution— run ffmpeg from command line with verbose logging on. Look for error messages. Google error messages. See if it only affects mp3 encoding. See if there is a better command line for ffmpeg command that doesn’t crash. (Maybe that doesn’t use LAME)  Run ffmpeg using debugger and set breakpoints where errors occur. Post on ffmpeg discussion board. Send a sample file to ffmpeg developer willing to debug it.

**Comment by Darthagnon** [comment] 2019-12-31 22:26
I've had the same issue, with Stephen Fry's reading of Sherlock Holmes. I successfully used [adiamus's AaxAudioConverter](https://github.com/audiamus/AaxAudioConverter) to convert it. (NB it has a weird activation requirement - needs some 8-digit Audible account token, which I have no idea where to find manually; this limits its use to Win10 PCs that can install the Audible UWP app, if AudibleManager refuses to "Activate" the PC.

**Comment by openaudible** [comment] 2020-01-01 19:00
I can't reproduce, so hard to fix without additional help. Latest version should be used (currently 1.6.4) as that includes new error logging.

Can you copy and paste the main error from the console output, or into a pastebin if you post the whole command? 

Running from the command line would be the easiest way to reproduce and help fix.  Look at our (complicated) ffmpeg command and get your activation_bytes. Then create a copy "test.AAX" of your problem file.

Then run:

`ffmpeg -activation_bytes XXXXXX -i "test.AAX" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -loglevel debug -v verbose test.mp3 `

If you get the same error, let us know by pastebin link to the output. 

Then feel free to change any arguments to see if it can work (remove lame codec) or try different output format.

Also, how long does it take to spit out an error? 

@Darthagnon if you can determine the ffmpeg command that aaxAudioConverter uses, let me know.

**Comment by benjaminewton** [comment] 2020-01-01 19:13
I would give this ago but sorry I'm not technical enough. In case it's of any help I just tried it again and it stopped 7:36 into a 19:36 book.

**Comment by Avilyn238** [comment] 2020-01-01 19:48
I'm getting the same error with 6 books out of my library (272 books total).  Console log attached.
[Console non-zero response error.txt](https://github.com/openaudible/openaudible/files/4014482/Console.non-zero.response.error.txt)

**Comment by openaudible** [comment] 2020-01-01 21:48
@Avilyn238 Thank you. That helps. 

This is an open [bug/error in the LAME MP3 encoder](https://sourceforge.net/p/lame/bugs/490/)

Which is deep in the LAME mp3 encoder in a function called [short_block_constrain](https://sourceforge.net/p/lame/svn/HEAD/tree/trunk/lame/libmp3lame/vbrquantize.c). 

This bug is also [reported here](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2018-January/038763.html) and has more info. 

The bug _may_ have been fixed [LAME bug 496](https://sourceforge.net/p/lame/bugs/496/) but I don't know when that source code change will go into ffmpeg. 

Sounds like downgrading ffmpeg to 3.3.4 might also help if someone wants to try. If you find a version that works, let me know the version on https://ffbinaries.com/downloads 

ffmpeg uses LAME for mp3 encoding by default, so I don't think I can just turn off LAME.

**Comment by openaudible** [comment] 2020-01-04 01:13
OK. I compiled ffmpeg from scratch which uses the latest lame library.
Can you give this a try?
https://openaudible.org/temp/OpenAudible_1.6.4_win.exe
As far as I know, this only affected windows users.
Let me know.

**Comment by parkylondon** [comment] 2020-01-04 09:09
Worked like a CHARM. Thank you!
Absolutely no issues to report.

**Comment by Avilyn238** [comment] 2020-01-04 16:07
Confirming the new version also solves this issue.  Thanks!

**Comment by ametueraspirant** [comment] 2020-01-10 06:42
this happened to me on water keep: farworld volume 1. but only on my laptop. on my pc it converted sucessfully.

**Comment by openaudible** [comment] 2020-01-10 19:53
@ametueraspirant Laptop also PC? Did you re-download 1.6.4?

**Comment by ametueraspirant** [comment] 2020-01-18 12:40
my laptop had the issue. the PC did not. and I did redownload 1.6.4

**Comment by openaudible** [comment] 2020-02-03 23:19
I updated the version of ffmpeg for 1.6.5. Feel free to erase and re-encode any or all mp3's.

**Comment by ametueraspirant** [comment] 2020-02-04 23:35
it works now. I updated and reencoded the failures without any errors. I didn't even have to redownload or delete anything.

**Comment by openaudible** [comment] 2020-05-17 23:59
This hell bug has come back in 2.0.7. It affects less than 1% of conversions. 
A pre-release is available if anyone is seeing this... https://openaudible.org/prerelease

**Comment by openaudible** [comment] 2020-05-20 05:18
Fixed in 2.0.8. Again.

**Closed by openaudible** 2020-05-20 05:18 UTC
