### ISSUE TITLE
No OpenAudible windows under XQuartz

### ISSUE THREAD

**Issue by goldharv** [openaudible/openaudible#318] opened 2020-04-12 21:24 UTC
OpenAudible works fine on OSx native.

I have been trying to get OpenAudible up on a VMWare Fusion 1.5.3 virtual Ubuntu 18.04 server running under OSx 10.15.3. When I run it via an SSH session logged into Ubuntu, I get:
OpenAudible 
Apr 12, 2020 2:06:05 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.0 for gtk swt 4930 jvm 11.0.6 file charset UTF-8

On Ubuntu, for the last few OpenAudible releases, I have seen the primary OpenAudible window, but when I try to log into Audible, the web interface is not usable.

The 2.0 version does not show any windows. For what it's worth, I normally run with several X windows, Firefox and Visual Slick Edit up. I test with xeyes and xclock.

**Comment by openaudible** [comment] 2020-04-12 21:35
Any other errors show up in the console? 

We have no way to reproduce this.. but error messages and googling the errors is what we would recommend. We use the latest "Eclipse SWT" libraries for cross platform java desktop.. so finding another SWT app that uses a browser might also yield some clues (or better error messages.) 

We use ubuntu 18.04 for testing, so that part should work.

**Comment by goldharv** [comment] 2020-04-13 15:03
I got better error messages:
harry@hawk-server:~$ OpenAudible
Apr 13, 2020 7:57:11 AM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.0 for gtk swt 4930 jvm 11.0.6 file charset UTF-8
Apr 13, 2020 7:57:12 AM org.openaudible.desktop.swt.gui.GUI <init>
SEVERE: Charset not set to utf-8
Apr 13, 2020 7:57:12 AM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 2.0
Apr 13, 2020 7:57:12 AM org.openaudible.Directories getPrefs
INFO: loaded settings 1582669035930
bg=Color {232, 232, 231, 255}
Apr 13, 2020 7:57:15 AM org.openaudible.Audible load
INFO: Loading /home/harry/OpenAudible/books.json
Apr 13, 2020 7:57:15 AM org.openaudible.Directories getPrefs
INFO: loaded settings 1582669035930
Apr 13, 2020 7:57:15 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1051 to disk:/home/harry/OpenAudible/tmp/saved_books.json
Apr 13, 2020 7:57:15 AM org.openaudible.Audible save
INFO: Save books took 23 ms. to complete.
Apr 13, 2020 7:57:15 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 319 to disk:/home/harry/OpenAudible/settings.json
Apr 13, 2020 7:57:15 AM org.openaudible.Audible checkLibrary
INFO: loaded 1 books.
Apr 13, 2020 7:57:16 AM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 1396 ms. to complete.
Apr 13, 2020 7:57:26 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Apr 13, 2020 7:57:47 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Apr 13, 2020 7:57:49 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan page completed:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:5215): Gdk-ERROR **: 07:58:04.186: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadRenderRequest'.
  (Details: serial 197 error_code 166 request_code 149 (GLX) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by openaudible** [comment] 2020-04-13 16:37
Looks like OA is not compatible with your system-- you may need to install additional software or patches. You can try googling the errors above. I'd start with: "libGL error: failed to load driver: swrast"

**Comment by openaudible** [comment] 2020-04-14 04:34
Closing.. but feel free to post a solution.. and its possible others having the same issue can find this from google and chime in.

**Closed by openaudible** 2020-04-14 04:34 UTC
