### ISSUE TITLE
OpenAudible Not Reading full library

### ISSUE THREAD

**Issue by kurt575** [openaudible/openaudible#492] opened 2020-11-29 19:20 UTC
OpenAudible does not read full library.  It reads 2-4 pages then hangs.

After the first attempt it continues to say it is connected to the library but if I try to do a full sync (or quick sync) it will not connect.  If I try to refresh info then it does connect (unable to connect right now try connecting from this web page....[I can see on the browser I am connected]).  

Seems to be an issue with the pop up browser. 

I am using latest version 2.3.5 with a clean / first time install on a Windows 10 machine.

**Comment by openaudible** [comment] 2020-11-29 23:19
If you have something like pi-hole (or adware blocking proxy/firewall) that can cause problems... But would need to see some logs where it is getting hung.

**Comment by steve5053872** [comment] 2020-12-19 19:47
I have installed 2.4.0.1beta and the issue is still present.  I have over 160 books, but after full library scan, OpenAudible list only 63 books.

**Comment by openaudible** [comment] 2020-12-20 16:19
OpenAudible only finds books you’ve purchased. Podcasts and free books are not allowed to be downloaded. 

If you use the OpenAudible browser to log into your audible account, any book that has a download link should be in your library and found by OpenAudible.

**Comment by openaudible** [comment] 2020-12-21 05:41
Closing. Fixed in beta. Will be fixed in next official release.

**Closed by openaudible** 2020-12-21 05:41 UTC

**Comment by kurt575** [comment] 2020-12-23 18:13
Thank you.  How can I get the beta, or do I need to wait until the next official release?


    On Monday, December 21, 2020, 12:42:06 AM EST, openaudible <notifications@github.com> wrote:  
 
 


Closing. Fixed in beta. Will be fixed in next official release.

**Comment by openaudible** [comment] 2020-12-23 19:57
https://openaudible.org/beta
(Or any version higher than 2.3.5 if the beta is closed)
