### ISSUE TITLE
Mac Intel Ventura crash on Connect

### ISSUE THREAD

**Issue by chafafa** [openaudible/openaudible#1050] opened 2022-10-29 22:37 UTC
program crashes when trying to connect to audible

**Comment by openaudible** [comment] 2022-10-30 11:16
Need a full crash log. What OS? There is a debug script you can run from the command line to get the last error.

**Comment by chafafa** [comment] 2022-10-30 14:50
How do I do that? You documentations says a log is sent. I’m running macOS Ventura. On Oct 30, 2022, at 7:16 AM, openaudible ***@***.***> wrote:﻿
Need a full crash log. What OS? There is a debug script you can run from the command line to get the last error.

**Comment by chafafa** [comment] 2022-10-30 15:41
ii just sent a report. I am not sure if it is the right one or not.

**Comment by openaudible** [comment] 2022-10-30 18:31
Looks like this has been reported a couple of times. #968 

I just installed Ventura and I am did not get a crash. So will need one or two good error logs to solve.

Can someone run OpenAudible from the terminal.app using the debug_mac.sh command line:
Open Terminal (by typing "Terminal" in the Mac Search bar and run the Terminal application) and paste: 
```
 /Applications/OpenAudible.app/Contents/Resources/app/debug_mac.sh
```
That should run OpenAudible from the terminal. Any crashes should produce an error at the end of the terminal.
Try to connect to Audible using the built in browser. If it crashes, go back to terminal.app and copy and paste the text.. and send it to openaudible at email dot tg.  (Or paste it here in a reply, making sure you obfuscate/delete anything that looks like a key or security code or any personal info.) 

Thanks in advance for your assistance!

**Comment by chafafa** [comment] 2022-10-30 20:04
For some reason the program does not crash when run from the terminal.  To sure how to proceed to get you the error Loog you need

**Comment by openaudible** [comment] 2022-10-30 21:08
That’s what the other reporter said… very strange.  Maybe a sandbox violation or something… are you Intel or m1?

**Comment by openaudible** [comment] 2022-10-30 21:46
A few things to try... 
If the debug_mac.sh doesn't cause a crash, if someone could try from Terminal:
```
/Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub
```
This should launch the program that is a little closer to what would happen if you double click the application. If you need to, Log out of Audible and Log back in.. Hopefully a crash will be detected.

Also, when you run the program, you can keep the OpenAudible console window open File: Console Window

When it does crash does the whole application disappear or is there an error message?

Also, when running OpenAudible, if you watch the output in the Console.app program, perhaps you'll see an error message that would be helpful.

If you're using a network drive to store your books, let me know that too.. 

Thanks again...

**Comment by chafafa** [comment] 2022-10-31 15:41
Intel

MacBook Pro
15 in, 2017

**Comment by blurfl** [comment] 2022-10-31 19:27
I can confirm the crash on an Intel Mac with Ventura and OA 2.6.2 or OA 3.6.2beta1. It occurs whether or not using an external browser. The crash occurs when running OA in the normal manner using the JavaApplicationStub, but not using the debug_mac.sh script. Because of the crash, the OA console is not available, but the JavaApplicationStub leaves some info in the terminal and saves a log file (see archive attached). 
[Archive.zip](https://github.com/openaudible/openaudible/files/9904198/Archive.zip)

**Comment by chafafa** [comment] 2022-10-31 19:40
So will you be releasing a version that corrects this issue or should I use the terminal as a workaround?

**Comment by blurfl** [comment] 2022-10-31 20:42
I'm a user, like you. Fixes here seem to come rapidly, and I've provided some info that might help to point to the issue. For now, I'll use the terminal for a workaround. I won't be surprised to see a new beta addressing this soon, though.

**Comment by openaudible** [comment] 2022-10-31 21:28
@blurfl Thank you for the great bug report. Those two files were exactly what I needed. 
The code failing is buried in a library. I will see if there is a newer version. I'll also find an Intel Mac to test with and see if I can reproduce-- doesn't seem to happen on m1 Mac's.
When there is a new beta version, I will probably ask to have to you log out and run again from the JavaApplicationStub.. 

@chafafa You should only need to run from terminal once until you're logged in. Until you log out, you shouldn't encounter that bug. 

Pasting the error here so that others running into it can find it from google and or look at others with similar issues:
```
Current thread (0x00007f7ec7836800):  JavaThread "main" [_thread_in_native, id=259, stack(0x00007ff7b6cea000,0x00007ff7b74ea000)]

Stack: [0x00007ff7b6cea000,0x00007ff7b74ea000],  sp=0x00007ff7b74e3af8,  free space=8166k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000045a3f1a440a4
C  [JavaScriptCore+0x55177c]  llint_entry+0x1d192
C  [JavaScriptCore+0x552615]  llint_entry+0x1e02b
C  [JavaScriptCore+0x55177c]  llint_entry+0x1d192
C  [JavaScriptCore+0x55177c]  llint_entry+0x1d192
C  [JavaScriptCore+0x5343e7]  vmEntryToJavaScript+0xd8
C  [JavaScriptCore+0xccf61d]  JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*)+0x45d
C  [JavaScriptCore+0xf7957a]  JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)+0xfa
C  [WebCore+0x111d70c]  WebCore::JSExecState::profiledEvaluate(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)+0x5c
C  [WebCore+0x111d3a8]  WebCore::ScriptController::evaluateInWorld(WebCore::ScriptSourceCode const&, WebCore::DOMWrapperWorld&)+0xc8
C  [WebCore+0x111d7a5]  WebCore::ScriptController::evaluateIgnoringException(WebCore::ScriptSourceCode const&)+0x35
C  [WebCore+0x149fa2a]  WebCore::ScriptElement::executeClassicScript(WebCore::ScriptSourceCode const&)+0x24a
C  [WebCore+0x146e1d7]  WebCore::LoadableClassicScript::execute(WebCore::ScriptElement&)+0x97
C  [WebCore+0x14a0049]  WebCore::ScriptElement::executePendingScript(WebCore::PendingScript&)+0x89
C  [WebCore+0x14a2ea8]  WebCore::ScriptRunner::timerFired()+0xb8
C  [WebCore+0x1b22978]  WTF::Detail::CallableWrapper<WebCore::ThreadTimers::setSharedTimer(WebCore::SharedTimer*)::$_0, void>::call()+0x98
C  [WebCore+0x968f]  WebCore::timerFired(__CFRunLoopTimer*, void*)+0x1f
C  [CoreFoundation+0x97996]  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__+0x14
C  [CoreFoundation+0x974fe]  __CFRunLoopDoTimer+0x334
C  [CoreFoundation+0x97114]  __CFRunLoopDoTimers+0x11d
C  [CoreFoundation+0x7da5c]  __CFRunLoopRun+0x832
C  [CoreFoundation+0x7cbb0]  CFRunLoopRunSpecific+0x230
C  [Foundation+0x5f49a]  -[NSRunLoop(NSRunLoop) runMode:beforeDate:]+0xd8
C  [libswt-pi-cocoa-4950r5.jnilib+0x15b29]  Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend_1bool__JJJJ+0x39
J 1758  org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(JJJJ)Z (0 bytes) @ 0x000000001af71a87 [0x000000001af719c0+0x00000000000000c7]
J 1762 c1 org.eclipse.swt.widgets.Display.sleep()Z (74 bytes) @ 0x0000000013d37694 [0x0000000013d368a0+0x0000000000000df4]
j  org.openaudible.desktop.swt.gui.GUI.runEventLoop()V+21
j  org.openaudible.desktop.swt.gui.GUI.run()V+18
j  org.openaudible.desktop.swt.manager.AppLoader.<init>([Ljava/lang/String;)V+429
```

**Comment by blurfl** [comment] 2022-10-31 21:35
I'll be happy to test.

**Comment by openaudible** [comment] 2022-11-01 19:32
Thanks. Closing this and will track this in issue: #968 since it was the original report and has a clear title.

**Comment by blurfl** [comment] 2022-11-02 23:55
OA 3.6.2.3beta on Intel Mac Ventura freezes during "Setting up browser environment for logging into Audible" after 'initialized' for the tmp/jcef-bundle. 'Cancel' has no effect, requires force-quit. Because of freeze, I only have a screen shot of the most recent part of the pertinent console log. Unable to test further.
![OA 3 6 3beta console](https://user-images.githubusercontent.com/1851315/199623528-1b035767-dfc7-4488-9f54-269eb96f157c.png)

<img width="777" alt="OA3 6 2 3beta screenshot" src="https://user-images.githubusercontent.com/1851315/199623818-a3359e7f-0dd5-4e1c-ae75-c431894c97a5.png">

**Comment by openaudible** [comment] 2022-11-03 05:03
@blurfl yeah, 3.6.2 was an attempt to use chrome browser.. works on linux and windows, but of course, Mac is being annoying. Sorry. Replaced with a 3.6.4 which still has a broken Intel/Ventura browser. Since this is solved, I'm deleting the image above.

I did post a bug report and hopefully will learn more:
https://bugs.webkit.org/show_bug.cgi?id=247387

**Comment by blurfl** [comment] 2022-11-03 06:26
I should have indicated that I'm using beta 13.1 on the Intel machine.
Sorry if I jumped the gun. Let me know if/when I can help.

**Comment by openaudible** [comment] 2022-11-15 00:20
New beta seems to have fixed it for the short term by using the JxBrowser library. 

OpenAudible Beta Version 3.6.2.5
https://openaudible.org/beta

**Closed** 2022-11-17 22:41 UTC
