### ISSUE TITLE
(suggestion) Convert audiobooks into tracks

### ISSUE THREAD

**Issue by Alucard2112** [openaudible/openaudible#186] opened 2019-09-02 23:37 UTC
For my archives I would prefer to habe the downloaded audiobooks split into tracks.
The information for that should be provided by the .aax file-format.
You could just add one checkbox into the preference to convert the audiobooks into different tracks within a folder of the name of the audiobook. If no information of the trackname is given, it could just be numerical like Track 1, Track 2, Track 3 etc.

**Comment by openaudible** [comment] 2019-09-03 04:02
I am working on a solution for something like that. The whole app is based on one file per book (actually, 1 aax, 1 mp3, 1 image file) But I am considering a join and split option to import audio books that are split.. and to allow splitting a book by chapters.  Some books do not contain chapter info, so then it has to be chopped into hour blocks or some other method, which leaves a book in the middle of a sentence. So it isn't easy.. but a simple utility may be the best bet.

**Comment by thscott** [comment] 2019-09-03 08:13
In case you're not aware, this is exactly what [AaxAudioConverter](https://github.com/audiamus/AaxAudioConverter) does, so perhaps some collaboration would be better than starting the feature from scratch.

**Comment by hungvanminh** [comment] 2019-09-03 17:16
Im using AAX Audio Converter and its awesome. One problem tho it cant split chapters/parts of a book with theirs titles/names as display in official Audible app. Not a huge issue but some books like **It** from Stephen King got over 200 files, kinda mess. Any solution on this? It'd be very nice!

**Comment by openaudible** [comment] 2019-09-03 22:46
Except for mp3 players with very limited memory (bluetooth earbuds?), I'm having a hard time understanding why 30 files in a folder is easier than using a single MP3 with a decent book player that keeps track of your playback position. As you can see from the screen shots, there are a lot of settings and personal preferences about length, naming, etc. The code to split isn't complex, but managing the options with a nice UI is the hard part.

**Comment by Alucard2112** [comment] 2019-09-03 23:16
Well, if the tracks are listed in aax, you could just split them accordingly by adding a simple checkbox in the preferences.
When nothing is listed in the aax, you could just leave them as one mp3 since people will most likely cut them manually ;)

**Comment by openaudible** [comment] 2019-09-09 16:25
@hungvanminh If you can find html code to extract the chapter names.. it would be nice.. especially if it was in some kind of json or easily parsed html.. I've only seen chapter names in the online audible audio player. Trying to load that page and extract the data looked tricky and prone to being broken.

**Comment by hungvanminh** [comment] 2019-09-13 20:31
I understand that. I'll be trying to look thru to find where the extract code is.

**Comment by safareli** [comment] 2019-09-17 11:51
It would also be great if user could convert `aax` to `m4b`.

**Comment by openaudible** [comment] 2019-09-22 17:48
I looked at finding out the chapter names. It is only possible (that I know) by invoking the cloud player. So far its just experimental.

I am working on some split/join code for a future release. 

Understand some people like m4b, which would complicate things as there would be multiple m4b's per audiobook.. but if I move to a more general purpose audio book manager, it would definitely be something to pursue.

**Comment by jimbo5678** [comment] 2019-09-25 19:06
For me, the advantage of having 30 files instead of one is navigation. If you can use track skip to go forward and backward by chapters, it can be very useful. Especially if you're, for example, listening on more than one device, or also reading on paper/ebook at other times, so you can quickly find a place.

**Comment by guysoft** [comment] 2019-10-06 16:54
Just for docs, related/duplicate of: https://github.com/openaudible/openaudible/issues/92

@openaudible Its great to know you are working on the feature!

**Comment by openaudible** [comment] 2019-10-14 00:49
Added a utility to join and split in 1.5.4

**Closed by openaudible** 2019-10-14 00:49 UTC
