### ISSUE TITLE
App icon bounces but does not start

### ISSUE THREAD

**Issue by chrift** [openaudible/openaudible#208] opened 2019-10-15 09:55 UTC
On MacOS Mojave 10.14.5

I have just installed openaudible but when I start the app the app icon just bounces in the app tray and when I right click on it it says "App is not responding"

Force closing the app and restarting restarts the behaviour.

**Comment by sirach39** [comment] 2019-10-15 19:42
I have this same issue on Mac Mojave 10.14.5.

**Comment by rockwoofstone** [comment] 2019-10-16 10:50
Same issue for me on MacOS Catalina 10.15

**Comment by Funky-Boss** [comment] 2019-10-16 16:56
Same issue, macOS Catalina 10.15.

**Comment by openaudible** [comment] 2019-10-16 17:52
Can you open "Console" and type "openaudible" in the upper right search box.
Re-launch OpenAudible.
Copy and paste any errors that are returned.. I am only testing on Catalina these days. 

You can also try right-clicking on the OpenAudible.app and selecting Open?

You might also need to adjust your GateKeeper settings.. Go to "Security & Privacy" and make sure "Allow apps downloaded from" App Store and identified developers. (Although we don't sign the app.)

**Comment by Funky-Boss** [comment] 2019-10-16 18:17
I tried he two options with no luck. I already had my security settings as "Allow apps downloaded" and I also tried right clicking and open. Below is what I copied from Console

default	12:02:18.441924-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 0;
        BundleID = "com.install4j.7008-5171-7013-3819.22";
        Hide = 0;
        Path = "/Applications/OpenAudible.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/System/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.readdle.smartemail-mac";
        Hide = 0;
        Path = "/Applications/Spark.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/System/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.word";
        Hide = 0;
        Path = "/Applications/Microsoft Word.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.ringcentral.ringcentralformac";
        Hide = 0;
        Path = "/Applications/RingCentral for Mac.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.excel";
        Hide = 0;
        Path = "/Applications/Microsoft Excel.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.glip.glip";
        Hide = 0;
        Path = "/Applications/Glip.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.amazon.music";
        Hide = 0;
        Path = "/Applications/Amazon Music.app";
    }
)
default	12:02:18.445281-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : OpenAudible
default	12:02:18.445338-0600	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: OpenAudible
default	12:02:18.445420-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: OpenAudible
default	12:02:18.456801-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 0;
        BundleID = "com.install4j.7008-5171-7013-3819.22";
        Hide = 0;
        Path = "/Applications/OpenAudible.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/System/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.readdle.smartemail-mac";
        Hide = 0;
        Path = "/Applications/Spark.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/System/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.word";
        Hide = 0;
        Path = "/Applications/Microsoft Word.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.ringcentral.ringcentralformac";
        Hide = 0;
        Path = "/Applications/RingCentral for Mac.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.excel";
        Hide = 0;
        Path = "/Applications/Microsoft Excel.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.glip.glip";
        Hide = 0;
        Path = "/Applications/Glip.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.amazon.music";
        Hide = 0;
        Path = "/Applications/Amazon Music.app";
    }
)
default	12:02:26.380810-0600	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:OpenAudible, _appTrackingState = 2
default	12:02:26.380845-0600	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: OpenAudible, quit, updating active tracking timer
default	12:02:31.382793-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 0;
        BundleID = "com.install4j.7008-5171-7013-3819.22";
        Hide = 0;
        Path = "/Applications/OpenAudible.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/System/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.readdle.smartemail-mac";
        Hide = 0;
        Path = "/Applications/Spark.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/System/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.word";
        Hide = 0;
        Path = "/Applications/Microsoft Word.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.ringcentral.ringcentralformac";
        Hide = 0;
        Path = "/Applications/RingCentral for Mac.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.excel";
        Hide = 0;
        Path = "/Applications/Microsoft Excel.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.glip.glip";
        Hide = 0;
        Path = "/Applications/Glip.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.amazon.music";
        Hide = 0;
        Path = "/Applications/Amazon Music.app";
    }
)
default	12:14:14.238351-0600	Finder	LAUNCHING:0x0-0x1f61f6 OpenAudible foreground=1 bringForward=1 seed=453 userActivityCount=0
default	12:14:14.247284-0600	loginwindow	-[PersistentAppsSupport applicationReady:] | App: OpenAudible, ready, updating active tracking timer
default	12:14:14.247726-0600	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : OpenAudible
default	12:14:14.780566-0600	JavaApplicationStub	FRONTLOGGING: version 1
default	12:14:14.780581-0600	JavaApplicationStub	Registering, pid=5104
default	12:14:14.781933-0600	JavaApplicationStub	CHECKIN: pid=5104
default	12:14:14.788234-0600	JavaApplicationStub	CHECKEDIN: pid=5104 asn=0x0-0x1f61f6 foreground=1
default	12:14:14.788964-0600	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : OpenAudible
default	12:14:14.798870-0600	JavaApplicationStub	Registered, pid=5104 ASN=0x0,0x1f61f6
default	12:14:14.799000-0600	JavaApplicationStub	Registered, pid=5104 cgConnectionID=e933b
default	12:14:14.800350-0600	JavaApplicationStub	BringForward: pid=5104 asn=0x0-0x1f61f6 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	12:14:14.800399-0600	JavaApplicationStub	BringFrontModifier: pid=5104 asn=0x0-0x1f61f6 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	12:14:14.800584-0600	JavaApplicationStub	BringForward: pid=5104 asn=0x0-0x1f61f6
default	12:14:14.800685-0600	JavaApplicationStub	SetFrontProcess: asn=0x0-0x1f61f6 options=0
default	12:14:14.809606-0600	JavaApplicationStub	Current system appearance, (HLTB: 2), (SLS: 1)
default	12:14:14.816487-0600	JavaApplicationStub	Post-registration system appearance: (HLTB: 2)
default	12:14:14.835551-0600	JavaApplicationStub	Registering for test daemon availability notify post.
default	12:14:14.835691-0600	JavaApplicationStub	notify_get_state check indicated test daemon not ready.
default	12:14:19.250642-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : OpenAudible
default	12:14:19.250663-0600	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: OpenAudible
default	12:14:19.250700-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: OpenAudible
default	12:14:19.261868-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 0;
        BundleID = "com.install4j.7008-5171-7013-3819.22";
        Hide = 0;
        Path = "/Applications/OpenAudible.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/System/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/System/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.readdle.smartemail-mac";
        Hide = 0;
        Path = "/Applications/Spark.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.word";
        Hide = 0;
        Path = "/Applications/Microsoft Word.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.ringcentral.ringcentralformac";
        Hide = 0;
        Path = "/Applications/RingCentral for Mac.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.microsoft.excel";
        Hide = 0;
        Path = "/Applications/Microsoft Excel.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.glip.glip";
        Hide = 0;
        Path = "/Applications/Glip.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.amazon.music";
        Hide = 0;
        Path = "/Applications/Amazon Music.app";
    }
)
default	12:14:24.831736-0600	JavaApplicationStub	LSExceptions shared instance invalidated for timeout.

**Comment by rockwoofstone** [comment] 2019-10-16 21:01
Here you go...

```
default	21:56:47.447473+0100	Dock	LAUNCHING:0x0-0xc80c8 OpenAudible foreground=1 bringForward=1 seed=259 userActivityCount=0
default	21:56:47.454768+0100	loginwindow	-[PersistentAppsSupport applicationReady:] | App: OpenAudible, ready, updating active tracking timer
default	21:56:47.454814+0100	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : OpenAudible
default	21:56:47.665800+0100	JavaApplicationStub	FRONTLOGGING: version 1
default	21:56:47.665813+0100	JavaApplicationStub	Registering, pid=47914
default	21:56:47.667186+0100	JavaApplicationStub	CHECKIN: pid=47914
default	21:56:47.672415+0100	JavaApplicationStub	CHECKEDIN: pid=47914 asn=0x0-0xc80c8 foreground=1
default	21:56:47.673296+0100	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : OpenAudible
default	21:56:47.684823+0100	JavaApplicationStub	Registered, pid=47914 ASN=0x0,0xc80c8
default	21:56:47.684951+0100	JavaApplicationStub	Registered, pid=47914 cgConnectionID=7fc27
default	21:56:47.686235+0100	JavaApplicationStub	BringForward: pid=47914 asn=0x0-0xc80c8 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	21:56:47.686279+0100	JavaApplicationStub	BringFrontModifier: pid=47914 asn=0x0-0xc80c8 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	21:56:47.686388+0100	JavaApplicationStub	BringForward: pid=47914 asn=0x0-0xc80c8
default	21:56:47.686487+0100	JavaApplicationStub	SetFrontProcess: asn=0x0-0xc80c8 options=0
default	21:56:47.689753+0100	JavaApplicationStub	Current system appearance, (HLTB: 1), (SLS: 0)
default	21:56:47.693006+0100	JavaApplicationStub	Post-registration system appearance: (HLTB: 1)
default	21:56:47.708261+0100	JavaApplicationStub	Registering for test daemon availability notify post.
default	21:56:47.708389+0100	JavaApplicationStub	notify_get_state check indicated test daemon not ready.
default	21:56:52.457339+0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : OpenAudible
default	21:56:52.457355+0100	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: OpenAudible
default	21:56:52.457385+0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: OpenAudible
default	21:56:52.462510+0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 0;
        BundleID = "com.install4j.7008-5171-7013-3819.22";
        Hide = 0;
        Path = "/Applications/OpenAudible.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
)
default	21:56:57.715128+0100	JavaApplicationStub	LSExceptions shared instance invalidated for timeout.
```

Then the icon just sits in the dock bouncing for a while, then locks up completely.

**Comment by openaudible** [comment] 2019-10-16 22:37
Thanks. I didn't see anything helpful in the Console output.. 

Lets try from Terminal.app. Copy and paste the code blocks (one at a time) into Terminal.

Try to start java launcher. Maybe see errors or some text output... 

```
/Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub
```



The second method tries to start the app using in the bundled jre. 

```
cd /Applications/OpenAudible.app/Contents/Resources/app

../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -version

../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -cp openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64-4.6.jar -XstartOnFirstThread -Dfile.encoding=UTF-8 org.openaudible.desktop.Application

```


Lastly, if you already have java installed on your mac, you can try the following:

```
cd /Applications/OpenAudible.app/Contents/Resources/app

java -version

java -cp openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64-4.6.jar -XstartOnFirstThread -Dfile.encoding=UTF-8 org.openaudible.desktop.Application

```

**Comment by whiskyfake** [comment] 2019-10-16 22:38
Same issue here. MacOS Catalina 10.15.

**Comment by openaudible** [comment] 2019-10-16 23:17
I also built a new installer you can try.. 
https://openaudible.org/temp/OpenAudible_macos_1_5_4.b.dmg

**Comment by Funky-Boss** [comment] 2019-10-17 03:54
I get a 404 error when clicking on the new installer.

Below is what I get when using each of the lines in Terminal. I hope
this helps.

/Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub

gordos-mac-mini:~ camille$
/Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub

java.lang.NoClassDefFoundError: org/eclipse/swt/SWT

at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:36)

at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:71)

at org.openaudible.desktop.Application.main(Application.java:22)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)

at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWT

at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

... 9 more


cd /Applications/OpenAudible.app/Contents/Resources/app

../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -version

gordos-mac-mini:app camille$
../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -version

java version "1.8.0_192"

Java(TM) SE Runtime Environment (build 1.8.0_192-b12)

Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)


../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -cp
openaudible-jar-with-dependencies.jar:org.eclipse.
swt.cocoa.macosx.x86_64-4.6.jar -XstartOnFirstThread -Dfile.encoding=UTF-8
org.openaudible.desktop.Application

gordos-mac-mini:app camille$
../../PlugIns/jre.bundle/Contents/Home/jre/bin/java -cp
openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64-4.6.jar
-XstartOnFirstThread -Dfile.encoding=UTF-8
org.openaudible.desktop.Application

Exception in thread "main" java.lang.NoClassDefFoundError:
org/eclipse/swt/SWT

at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:36)

at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:71)

at org.openaudible.desktop.Application.main(Application.java:22)

Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWT

at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

... 3 more


java -version

gordos-mac-mini:app camille$ java -version

java version "13.0.1" 2019-10-15

Java(TM) SE Runtime Environment (build 13.0.1+9)

Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)


java -cp openaudible-jar-with-dependencies.jar:org.eclipse.
swt.cocoa.macosx.x86_64-4.6.jar -XstartOnFirstThread -Dfile.encoding=UTF-8
org.openaudible.desktop.Application

gordos-mac-mini:app camille$ java -cp
openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64-4.6.jar
-XstartOnFirstThread -Dfile.encoding=UTF-8
org.openaudible.desktop.Application

Exception in thread "main" java.lang.NoClassDefFoundError:
org/eclipse/swt/SWT

at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:36)

at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:71)

at org.openaudible.desktop.Application.main(Application.java:22)

Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWT

at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)

at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

... 3 more

**Comment by Funky-Boss** [comment] 2019-10-17 04:14
The new installer worked great! Thanks for the quick response on this issue!!!

**Comment by openaudible** [comment] 2019-10-17 04:23
Thanks for the feedback. Will review and replace the installer.

**Comment by whiskyfake** [comment] 2019-10-17 06:13
> I also built a new installer you can try..
> https://openaudible.org/temp/OpenAudible_macos_1_5_4b.dmg [edited]

That worked, thank you!

**Comment by rockwoofstone** [comment] 2019-10-17 08:13
The new installer sorted the problem for me too - thanks!

**Closed** 2019-10-17 14:33 UTC
