### ISSUE TITLE
Updating Cache forever

### ISSUE THREAD

**Issue by edpowell** [openaudible/openaudible#596] opened 2021-03-28 21:07 UTC
On macOS 11.2.3, I updated from 2.3.5 to 3.0.  Version 2.3.5 was working fine.

 I have 430 audio books in my existing library.  When starting 3.0, I get the following error:

Error loading books from file:
/<place>/books.json
File may be damaged.  Error:null

(I haven't touched the file.)

I click "OK" and am presented with another dialog box:

java.lang.NullPointerException

I click "OK" and a third dialog box appears:

(i) icon   Running task
Updating Cache

When a pointer overlays this dialog box, I get the Beach Ball of Doom.

I've let it run for 24 hours, but it's hung.  The "Cancel" button does not function.  Only way out is to Force Quit.

Thanks for your help.
![Screen Shot 2021-03-28 at 5 06 31 PM](https://user-images.githubusercontent.com/29112847/112768048-0391bf00-8fe8-11eb-8e1e-52577c95ca7d.jpg)

**Comment by openaudible** [comment] 2021-03-28 22:58
There is a bug somewhere. Would like to get the full bug report from the console (after it says may be damaged). If you can reproduce it (don't wait 24 hours!) send a bug report from the help menu. Thanks for the heads up.

**Comment by edpowell** [comment] 2021-03-30 17:53
I can't get to the console or the help menu.  Here's a screen vid:

https://user-images.githubusercontent.com/29112847/113033663-42965080-915f-11eb-82a8-47fc0de88e58.mp4

**Comment by openaudible** [comment] 2021-03-31 14:08
It looks like your "books.json" file is damaged or has a problem. You may need to back up your preferences and start again. 

Its possible the disk is not readable or the file locations changed. 

Would be nice to see the full error log after cancel.

You can run it in debug mode by doing the following:

Open Terminal.app

```
cd /Applications/OpenAudible.app/Contents/Resources/app
./debug_mac.sh
```

After you get to that point, hit cancel. I assume the cancel button doesn't work? 

Thanks for the report.

**Comment by edpowell** [comment] 2021-03-31 15:30
It's not my day.
![Screen Shot 2021-03-31 at 11 29 43 AM](https://user-images.githubusercontent.com/29112847/113170299-6e274280-9214-11eb-8a40-0a7fa7bb347c.jpg)

**Comment by openaudible** [comment] 2021-03-31 17:29
Looks like we have a bad debug_mac.sh script (well, it uses your system's slightly older java, instead of the one we include.)

Try the following:
```
cd /Applications/OpenAudible.app/Contents/Resources/app
../jre.bundle/Contents/Home/bin/java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64.jar" -XstartOnFirstThread  -Dfile.encoding=UTF-8 org.openaudible.desktop.Application

```

**Comment by edpowell** [comment] 2021-03-31 17:45
Thanks.  Progress, though the Cancel button causes the never-ending beach ball.

(base) [edpowell@iMac-Pro app]$  ../jre.bundle/Contents/Home/bin/java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.cocoa.macosx.x86_64.jar" -XstartOnFirstThread  -Dfile.encoding=UTF-8 org.openaudible.desktop.Application
Mar 31, 2021 1:42:50 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.0 for cocoa swt 4940 jvm 12 file.encoding UTF-8
Mar 31, 2021 1:42:51 PM org.openaudible.Directories isValid
SEVERE: Not found:/Volumes/Data/Music/Audio Books DRM Removed/books
Mar 31, 2021 1:42:51 PM org.openaudible.Directories cleanMetaDir
INFO: Delete unused empty directory: /Users/edpowell/Library/OpenAudible/books
Mar 31, 2021 1:42:51 PM org.openaudible.Directories cleanMetaDir
INFO: Delete unused empty directory: /Users/edpowell/Library/OpenAudible/M4B
Mar 31, 2021 1:42:51 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.0
Mar 31, 2021 1:42:51 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/edpowell/Library/OpenAudible/settings.json exists=true size=459
Mar 31, 2021 1:42:51 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1579132086928
Mar 31, 2021 1:42:52 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/edpowell/Library/OpenAudible/settings.json exists=true size=459
Mar 31, 2021 1:42:52 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1579132086928
Mar 31, 2021 1:42:52 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Mar 31, 2021 1:42:52 PM org.openaudible.Audible load
INFO: Loading /Volumes/Data/Music/Audio Books DRM Removed/books.json
Mar 31, 2021 1:42:52 PM org.openaudible.Audible load
SEVERE: Error loading
java.lang.NullPointerException
	at org.openaudible.bookfiles.BookDirectory.scanDirectory(BookDirectory.java:135)
	at org.openaudible.bookfiles.BookDirectory.scan(BookDirectory.java:72)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:110)
	at org.openaudible.bookfiles.BookFiles.updateFileCache(BookFiles.java:83)
	at org.openaudible.bookfiles.BookFiles.checkFileCache(BookFiles.java:218)
	at org.openaudible.bookfiles.BookFiles.getMediaFiles(BookFiles.java:150)
	at org.openaudible.bookfiles.BookFiles.getMediaFileCount(BookFiles.java:155)
	at org.openaudible.Audible.aaxCount(Audible.java:788)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.update(LibraryStatsManager.java:100)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.updateAll(LibraryStatsManager.java:191)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.booksUpdated(LibraryStatsManager.java:226)
	at org.openaudible.books.BookNotifier.booksUpdated(BookNotifier.java:102)
	at org.openaudible.Audible.takeBooks(Audible.java:505)
	at org.openaudible.Audible.takeBooks(Audible.java:474)
	at org.openaudible.Audible.loadBooks(Audible.java:517)
	at org.openaudible.Audible.load(Audible.java:595)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:1393)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1465)

Mar 31, 2021 1:42:52 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error loading books
Error loading books
Mar 31, 2021 1:42:52 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} visible=true input shell:Shell {OpenAudible}
Mar 31, 2021 1:42:55 PM org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Mar 31, 2021 1:42:55 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error starting
java.lang.NullPointerException
	at org.openaudible.bookfiles.BookDirectory.scanDirectory(BookDirectory.java:135)
	at org.openaudible.bookfiles.BookDirectory.scan(BookDirectory.java:72)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:110)
	at org.openaudible.bookfiles.BookFiles.updateFileCache(BookFiles.java:83)
	at org.openaudible.bookfiles.BookFiles.checkFileCache(BookFiles.java:218)
	at org.openaudible.bookfiles.BookFiles.getMediaFiles(BookFiles.java:150)
	at org.openaudible.bookfiles.BookFiles.getMediaFileCount(BookFiles.java:155)
	at org.openaudible.Audible.aaxCount(Audible.java:788)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.update(LibraryStatsManager.java:100)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.updateAll(LibraryStatsManager.java:191)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.booksUpdated(LibraryStatsManager.java:226)
	at org.openaudible.books.BookNotifier.booksUpdated(BookNotifier.java:102)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:1405)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1465)

Mar 31, 2021 1:42:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory showError
SEVERE: showError
java.lang.NullPointerException
	at org.openaudible.bookfiles.BookDirectory.scanDirectory(BookDirectory.java:135)
	at org.openaudible.bookfiles.BookDirectory.scan(BookDirectory.java:72)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:110)
	at org.openaudible.bookfiles.BookFiles.updateFileCache(BookFiles.java:83)
	at org.openaudible.bookfiles.BookFiles.checkFileCache(BookFiles.java:218)
	at org.openaudible.bookfiles.BookFiles.getMediaFiles(BookFiles.java:150)
	at org.openaudible.bookfiles.BookFiles.getMediaFileCount(BookFiles.java:155)
	at org.openaudible.Audible.aaxCount(Audible.java:788)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.update(LibraryStatsManager.java:100)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.updateAll(LibraryStatsManager.java:191)
	at org.openaudible.audible.bookstatus.LibraryStatsManager.booksUpdated(LibraryStatsManager.java:226)
	at org.openaudible.books.BookNotifier.booksUpdated(BookNotifier.java:102)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:1405)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1465)

Mar 31, 2021 1:42:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error
Mar 31, 2021 1:42:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} visible=true input shell:Shell {OpenAudible}
Mar 31, 2021 1:42:56 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 4609 ms. to complete.
Exception in thread "main" java.lang.NullPointerException
	at org.openaudible.bookfiles.BookDirectory.scanDirectory(BookDirectory.java:135)
	at org.openaudible.bookfiles.BookDirectory.scan(BookDirectory.java:72)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:110)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:239)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:691)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:280)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshFiles(AudibleGUI.java:1787)
	at org.openaudible.desktop.swt.manager.HintManager.checkHints(HintManager.java:44)
	at org.openaudible.desktop.swt.manager.HintManager.applicationStarted(HintManager.java:31)
	at org.openaudible.desktop.swt.manager.AudibleGUI.applicationStarted(AudibleGUI.java:1510)
	at org.openaudible.desktop.swt.manager.Application.applicationStarted(Application.java:79)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:515)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:103)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:113)
	at org.openaudible.desktop.Application.main(Application.java:41)
Mar 31, 2021 1:42:59 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
(base) [edpowell@iMac-Pro app]$

**Comment by edpowell** [comment] 2021-03-31 17:58
The only other thing is the directory is not on the main drive because it's too big.  So I use a link to a location on a second (Thunderbolt) external drive.
![Screen Shot 2021-03-31 at 1 57 09 PM](https://user-images.githubusercontent.com/29112847/113189373-22cb5f00-9229-11eb-8765-f9d8c8a10121.jpg)

**Comment by openaudible** [comment] 2021-03-31 21:44
There may be a case sensitivty problem.. that causes an unexpected problem. Mac is a case-sensitive file system. Generally we use uppercase for all directories.. Maybe rename M4B to m4b ?  I might have found the nullpointer bug.. So will release a new beta shortly.

**Comment by edpowell** [comment] 2021-03-31 21:54
We're getting there.  Please post an example directories.json file for 3.0.  I think you changed/added things in 3.0 that it's barfing on.

**Comment by openaudible** [comment] 2021-04-01 04:39
Ok. I posted a possible fix at https://openaudible.org/beta 
Hopefully get some error messages and further progress.

**Comment by edpowell** [comment] 2021-04-01 17:17
This now works, though there are some issues with duplicates.  Probably my fault as one of the troubleshooting steps I took was to delete the books.json file.  I can deal with that, though.  Thanks for your help!

**Comment by openaudible** [comment] 2021-04-02 15:40
Great! Closing. You can select duplicates and action menu delete to delete a book and all its files.

**Closed by openaudible** 2021-04-02 15:40 UTC
