### ISSUE TITLE
cant buy license 

### ISSUE THREAD

**Issue by Rorionstar** [openaudible/openaudible#789] opened 2021-12-03 04:48 UTC
i try to buy a license and i just get a blank screen,   also when i try to connect to amazon.com it comes with error  creating virtual device

**Comment by openaudible** [comment] 2021-12-03 18:42
Are you on Linux?  There is a known bug #782 in some Ubuntu distros that requires a missing library. 

The link to the store is https://openaudible.org/purchase

Good idea to make sure that virtual device error doesn't happen before you purchase. If that fix in 782 doesn't fix it, let me know what platform and region you're on.

**Comment by Rorionstar** [comment] 2021-12-03 19:58
I am on windows 10 pc I'm in Indiana.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by openaudible** [comment] 2021-12-03 23:21
You may need to make sure you've deleted any extra devices you've created. 
https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app?language=en_US

**Comment by Rorionstar** [comment] 2021-12-04 00:39
i have gone into amazon and deregister everything except current and it still wont allow me to log into amazon , still gives me the virtual device error msg ,

**Comment by Rorionstar** [comment] 2021-12-04 03:55
well for a few times i was able to log into amazon but now its back to virtual device error and i  still cant buy the lincense its just blank everytime i goto purchase

**Comment by openaudible** [comment] 2021-12-04 18:50
Once logged in you shouldn’t have to re-login. Don’t erase your credentials without logging out first. 
Use a different browser if having trouble buying. Strange stuff b

**Comment by MrFly** [comment] 2021-12-07 08:50
Same problem here on Ubuntu 20.04 - gstreamer plugin was already installed. The browser is broken, at login and any other browser operations.

How to fix it?

**Comment by abs0** [comment] 2021-12-14 20:13
Looks like this is an artifact of the embedded (IE?) window in which the licence information is shown on Windows. Can easily reproduce on a Windows 10 box with the latest version, and 3.0.1.

Seems to be related to https://bookmanager.onfastspring.com/ URLs - other https URLs are fine. Could it be certificate related?

**Comment by openaudible** [comment] 2021-12-17 04:32
Anything printed on the console log or a screenshot showing the error? Unable to reproduce here. But the internal browser is pretty lame— it’s all we have to work with.

**Comment by openaudible** [comment] 2022-01-03 23:59
This is a FastSpring.com bug that they are saying they won’t fix. We submitted a report to them with the exact lines of code that are incompatible. Not happy. 

For now, copy and paste the upgrade url into your desktop browser.

**Comment by abs0** [comment] 2022-01-04 10:03
A workaround could be to have the Windows version just pop open a dialog with a URL to open in the desktop browser? Seems like quite a nasty barrier for a new user trying to purchase

**Comment by openaudible** [comment] 2022-01-29 23:13
This should be fixed in 3.4 and higher.. But unfortunate for earlier versions..

**Closed by openaudible** 2022-01-29 23:13 UTC
