### ISSUE TITLE
2.4.1.0 Issues

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#536] opened 2021-01-26 18:39 UTC
Every time I restart the app, the Output and Automation preferences revert to MP3 and Automatically Convert AAX files, I change them but they revert on next load.  Even if I change the web or library location, these locations change after reload, but Output and Automation preferences do not reflect the changes made.

It is much safer to either include all of the preferences when saving, or at least set the defaults to have all of the automation options off.  

Am I missing something in the usage of the preferences file?

**Comment by wwalker** [comment] 2021-01-26 20:06
If you are on linux, as a temporary measure, until there is a fix in OpenAudible, you could try:
```
sudo chattr +i settings.json
```

But, it may cause OA to crash...to undo that is just
```
sudo chattr -i settings.json
```

**Comment by oboe45** [comment] 2021-01-26 20:36
A safer solution, which I already use is just to make sure that the
settings match my expectations every time I start OA, I will wait for a fix
and use the inconvenient process of resetting the preferences every time!

Not sure if making the file immutable would work on the mac anyway without
causing a crash in OA.

Thanks anyway

**Comment by openaudible** [comment] 2021-01-28 01:24
This is a duplicate of #539 ... So closing this.. Comment on 539 if you can with the new beta.

**Closed by openaudible** 2021-01-28 01:24 UTC
