### ISSUE TITLE
Right-clicking on an audiobook to change status to eg 'in queue' does not update Library Status 

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1127] opened 2023-02-10 17:22 UTC
i did report this issue before i had a thought that the events are just not calling the update code everywhere it needs to be called

When you right click on an audio book to change an audiobook from eg
status = error downloading to in download queue
to
status = In download queue

1. the status text updates in the audiobook info section - good
2. the library status window does not refresh to show the correct counts for to download, downloading etc - issue

Clicking on the links in the library status window does cause the data in the library status window to refresh

so the right-click menu code is not calling the update routine that the links events are calling....? this is a guess as a programmer

**Comment by openaudible** [comment] 2023-02-10 19:19
This sounds vaguely familiar. This may be fixed in the latest beta.. As I can't reproduce on beta with "start download, click cancel job"... then restart the download. Will do some more testing.

**Comment by feldegast** [comment] 2023-02-11 04:25
they go out of sync when downloads fail and the app downloads the next audiobook in the queue

**Comment by feldegast** [comment] 2023-02-11 04:31
i am not clicking cancel, it is failing by itself, possibly due to poor internet

**Comment by feldegast** [comment] 2023-02-12 05:33
cancel download does update downloading count

**Comment by openaudible** [comment] 2023-02-14 01:39
I think that is the expected behavior--otherwise files with 404 errors or other download problems will show as being available to download... so once a book turns red due to a download issue, it is removed from the "to download" queue. 
But regular timeout issues should automatically be "retried". So just sort by status and select the red ones and re-try to download.

**Closed by openaudible** 2023-02-14 01:39 UTC
