### ISSUE TITLE
Not able to connect to the legacy Audible account

### ISSUE THREAD

**Issue by DrRipCurl** [openaudible/openaudible#593] opened 2021-03-22 08:14 UTC
Hello,
I have exactly the same problem as "Gargoyle112" .
legacy user - Germany - Audible.de
same problem withe connecting to audible
[Red Error Cross] Unable to register a device.

and it is no problem to login on the audible website with my account, so....

what can I do?

**Comment by openaudible** [comment] 2021-03-22 15:48
Duplicate of #519. Looking into the problem.

**Closed by openaudible** 2021-03-22 15:48 UTC
