### ISSUE TITLE
Audible is changing file format

### ISSUE THREAD

**Issue by felthamn1** [openaudible/openaudible#397] opened 2020-06-17 21:38 UTC
Apologies if this is not the right place to post but this is a heads up. By the sounds of this email I got from audible customer care it will potentially become an issue. 

"Our records show that in the past, you may have downloaded your Audible titles on your Windows PC in an older audio format we call “format 4”. In the upcoming weeks, we will be moving all downloads to an enhanced, high-quality audio format and will no longer support format 4 downloading.

We’re excited about providing you with this higher-quality listening experience. If you prefer to listen to your Audible titles in format 4 audio, you will want to download them all to your device before we make the switch on 30/06/2020. 

You can continue downloading using the Audible Manager software on your computer if you would like, but you will need to make sure you are downloading in Enhanced format. If you switch to a different computer in the future, you will need to download a new software called AudibleSync, which we are working on now."

**Comment by openaudible** [comment] 2020-06-17 23:33
Duplicate of #375

**Closed by openaudible** 2020-06-17 23:33 UTC
