### ISSUE TITLE
Conversion has stopped working after latest update

### ISSUE THREAD

**Issue by HassoEccard** [openaudible/openaudible#1328] opened 2024-01-13 23:18 UTC
Hi
I've just updated to 4.0.1 on Intel Mac (Sonoma 14.2.1). 
When convert runs, it runs all the way through the book, says it's done, and then it starts again. It never creates the final mp3 file.
I've checked the directories, and they're fine. While the conversion is happening, the 'tmp' directory contains what looks like a relevant temporary file. There is sufficient disk space. 
It just goes round and round and round.
What can I do?

**Comment by openaudible** [comment] 2024-01-14 00:13
Disk is the usual issue so I’m not sure. 

Check the File: Log window for any errors or progress. Feel free to copy and paste or send a message to support.

**Comment by HassoEccard** [comment] 2024-01-14 19:40
[log.txt.zip](https://github.com/openaudible/openaudible/files/13932900/log.txt.zip)
There seem to be some errors, but I don't know what they mean

**Comment by youremumbling** [comment] 2024-01-14 23:56
I have the same issue. Some files work. But others failed. But I was able to import the .aax file manually and convert to mp3. Then I could convert the mp3 to m4b. The conversion took several minutes when it usually takes just seconds.

**Comment by openaudible** [comment] 2024-01-15 00:47
Hmm. Converting aax to m4b should be fast. Aax to mp3 and mp3 to m4b slow. Did you get the aax manually from android or using OpenAudible? Will take a while to review that log file. Nothing obvious jumped out. Which regions are you in?

**Comment by youremumbling** [comment] 2024-01-15 04:48
I got the file using OpenAudible. Other files came in at the same time and they processed with no issues. I've attached a log file of when I opened the program and it tried to convert.
[Open Audible Log.txt](https://github.com/openaudible/openaudible/files/13934927/Open.Audible.Log.txt)

**Comment by HassoEccard** [comment] 2024-01-16 02:06
> Hmm. Converting aax to m4b should be fast. Aax to mp3 and mp3 to m4b slow. Did you get the aax manually from android or using OpenAudible? Will take a while to review that log file. Nothing obvious jumped out. Which regions are you in?

via OpenAudible.
UK

**Comment by HassoEccard** [comment] 2024-01-16 12:48
Manually downloading the files, and running them on a windows 11 machine worked fine.

**Comment by youremumbling** [comment] 2024-01-17 01:35
I perform a complete uninstall and a clean install on my Mac and everything is fine now.

**Comment by openaudible** [comment] 2024-01-18 22:53
OK. Got another report of this. I did see that a cancel Job command was called.. so I added a bunch of error logging to the latest beta (4) to see if I can see who/what/where that is coming from. 

Please give the beta a try and if you can get the same behavior (conversion starts/stops/retries) please send a copy of the log. You can send directly to us as well.. but will be looking for any cancel messages in the File: Debug Log.

https://openaudible.org/beta

**Comment by HassoEccard** [comment] 2024-01-19 00:35
[log.txt.zip](https://github.com/openaudible/openaudible/files/13982921/log.txt.zip)

**Comment by openaudible** [comment] 2024-01-19 01:03
Hi @HassoEccard ...  It shows that you canceled the conversion for one of the books about Crazy Horse. 
Is it possible you used CTRL-period ? Or used the Action Menu to Cancel Jobs?

**Comment by HassoEccard** [comment] 2024-01-19 01:08
I cancelled it after the first conversion  completed, and the second had just started. I used the right-click pop-up menu 'Cancel 'Job'. I'll run it again cancel it when the second conversion starts, using the  'Action Menu'-> Cancel Job?

**Comment by HassoEccard** [comment] 2024-01-19 01:29
[log.txt.zip](https://github.com/openaudible/openaudible/files/13983220/log.txt.zip)

**Comment by HassoEccard** [comment] 2024-01-19 01:29
[log 2.txt.zip](https://github.com/openaudible/openaudible/files/13983223/log.2.txt.zip)

**Comment by openaudible** [comment] 2024-01-19 01:30
I don’t want you to cancel. Not sure why you did. 

Trying to find a bug where a conversion stops and restarts without user intervention. Or behavior that is not expected. Haven’t been able to reproduce anything.

**Comment by HassoEccard** [comment] 2024-01-19 01:49
ok, the first of the 2 I just sent was copied while the second conversion was running.

**Comment by openaudible** [comment] 2024-01-19 19:43
Ok. Think I got it. 
that file seems to be failing to convert. The app was failing to remove it from the todo list and it kept trying to convert it. New beta should fix it: https://openaudible.org/beta 

why it failed to convert is it looks like it might have been grabbed from an android or other download app. Or it belongs to another account or you’re not logged in. 

Give it a try and let me know. Thanks for the help reading it down.

**Comment by tetra-archos** [comment] 2024-01-19 20:19
Still having the same issue on the new beta, I didn't import the file it was automatically downloaded in a sync.

**Comment by openaudible** [comment] 2024-01-20 19:11
OK. Finally got it. This affects old users using the mp3/m4b directories and auto-convert on.
Fixed in https://openaudible.org/beta beta 6. Will be fixed in 4.0.2 once I get a confirmation.

**Comment by openaudible** [comment] 2024-01-20 22:58
Fixed in 4.0.2 and above. Thanks everyone.

**Closed by openaudible** 2024-01-20 22:58 UTC
