### ISSUE TITLE
Not finding all books?

### ISSUE THREAD

**Issue by seannymurrs** [openaudible/openaudible#99] opened 2019-02-23 22:06 UTC
OpenAudible didn't seem to be finding all of the books in my library. If I open the browser, and change the sort order, a full scan finds a few more books, but still not all of them.

**Comment by danchev** [comment] 2019-02-24 17:08
In the menu try Controls then Full Library Sync.
![image](https://user-images.githubusercontent.com/12420863/53302514-6a9a8380-3824-11e9-97d2-18440f95676f.png)

**Comment by seannymurrs** [comment] 2019-02-24 17:10
I have tried that many, many times. As I said, it will occasionally find one or two more when I do a full scan, but there are quite a few still missing.

-- Sean Murray
On Sun, Feb 24, 2019 at 12:08 PM, danchev <notifications@github.com> wrote:
In the menu try Controls then Full Library Sync.
[https://user-images.githubusercontent.com/12420863/53302514-6a9a8380-3824-11e9-97d2-18440f95676f.png]

**Comment by openaudible** [comment] 2019-02-25 00:53
There are a lot of diagnostic information logged to the console when a library page is parsed. Open the console from the file menu. Go to a library page that contains a book that isn't in your library. Look at the log.. It should log a bunch of information, including the name of the book you're trying to have added. Reply here with the output of the console with regards to that book. It might say, skipped because it is a partial book (maybe we are wrong?) or some other reason we skip books. Maybe it doesn't even show up in the list of books when we "next" through them. 

If you think you have found a bug, we can look at a bug report. To get it fixed, find a book not being added and use that as the key to the bug. Ideally if it is on the first page of your library. Restart OpenAudible. Open the browser. Move it to the side so you can watch for the missing book. Do a full library scan. When you see the book in the browser, click cancel (or wait for it to finish). Double check it wasn't added to your library. Go to the Help Menu and Submit a bug. Reference #99 and write Library did not find book with title: "name of the book". We can take a look for at the library files and step through the code to see what happened.

**Comment by seannymurrs** [comment] 2019-02-25 16:42
I managed to figure out a workaround, though I'm still not exactly sure what the issue is/was. I noticed that, when the browser page was open, if I manually clicked through each page of my library, the book count in OpenAudible would increase. I just had to manually click through all of my library pages to get all my books to show up. I'm assuming the full sync is supposed to automatically do what I did, but for some reason, it wasn't working.

**Comment by openaudible** [comment] 2019-02-25 19:08
Correct-- the full scan is supposed to click "next" through your whole library. We've had a few reports where that doesn't work. 

A quick scan is supposed to click next until no new books are found-- which assumes you are sorting by recently purchased.

Will leave this open for a while.. if anyone is seeing this, a bug report using steps from above would help reproduce and fix.

**Comment by madjo80** [comment] 2019-03-02 22:01
I did a full library scan a few times as well but that didn't add all my books, either. Seannymurrs workaround does work however! 

But that also makes it impossible to go to a library page of a book that OpenAudible hasn't scanned yet, because as soon as you open up the next or previous page of your library, the books get indexed and now it shows up in your library.

**Comment by catatized** [comment] 2019-03-07 21:11
I just updated OpenAudible. All my books are downloaded and they have been converted to mp3. The mp3's are in '//user/openaudible/mp3' which is set as the web/mp3 folder in 'preferences'. When I open the latest version of OA, it shows only 2 out of 12 books converted and 10 ready for conversion? I've tried resetting the folder, closing and reopening the program, etc. 
Why is it not detecting the mp3's it has already converted?
![oa_image](https://user-images.githubusercontent.com/48334561/53989263-6e5abf80-40da-11e9-9d50-afcb9d0984ce.jpg)
![oa_mp3_list](https://user-images.githubusercontent.com/48334561/53989280-76b2fa80-40da-11e9-9638-f51702e7cb92.jpg)

**Comment by openaudible** [comment] 2019-03-12 20:11
The web mp3 folder can't be the working directory "mp3" directory. We are working on a better file naming system.. but the web export is supposed to be a separate copy of all mp3's.

**Comment by openaudible** [comment] 2019-04-02 16:13
Added better bug report feature, so if this still happens, send a bug report from the help menu.

**Closed by openaudible** 2019-04-02 16:13 UTC

**Comment by jay-76** [comment] 2023-09-26 02:33
same issue,
L mint 21 5.19 core
had login issues, switched back to v 3.3 logged in, 
installed 3.9 was still logged in, (just license redo) and still after refresh, the latest books dont show up, .. yes i have 600+ books,and 500 on ignore, but the latest 2 are new bought. checked the console,
copy/paste fulltext search for "silver" and "spore" nope,none of the 2 found/seen 

how i got around atm, i used the webpage, downloaded the aax, and importet them,then refresh.. (control>refresh or F5)
then just accept the new books,and they are in. but its not a solution for the issue,but a short get around... for now (too much hassle in the long run)

**Comment by openaudible** [comment] 2023-09-26 02:48
If anyone sees this and is using the latest version and hasn’t logged out and back in, do a full rescan from the control menu and send a bug report with the name of a missing book. Thanks.

**Comment by jay-76** [comment] 2023-09-26 02:52
for me its those two
[Sporemageddon Vol. 1: Sporemageddon, Book 1]
[Silvers: Quest Academy, Book 1]

last time it worked for me 9.20. and next check was 25. and it didnt work 

if you need a console part,let me know which one, i simply dont wanne dump my whole console log with all my data in here (and the 2 dont even show up there)

**Comment by openaudible** [comment] 2023-09-26 02:56
So when you do a full rescan, I’d love the log if there is any error. Normally it gets each page of your library. It may be failing to get the first page or second page. Or maybe it gets them all but somehow skips the book. You can copy and paste the results from the full rescan and just send it via our contact for or to info at openaudible dot org. Redact as much as you want. If we can’t do a full rescan, we should put up an error message to log out and back in.

**Comment by jay-76** [comment] 2023-09-26 03:06
i did send the log, not redacted,but with the header "the log you asked for, in the github posting issue 99"
however i did add the 2 books via hand,as i described, so.. iam unsure if this helps now

**Comment by jay-76** [comment] 2023-10-04 13:04
9.3 fixed that one for me, thanks for htat. i get now all my books and who would have known,iam at 864 books... ,thanks again OA-Dev

**Comment by SimonBard** [comment] 2025-05-19 11:51
Is it normal that podcasts are not shown in the openaudible library? 
In the browser in audible, I can see them. Just noch in openaudible. 

Is there another chance to download them?

**Comment by openaudible** [comment] 2025-05-19 14:05
They can be a little messy so you have to enable them in the Manage Libraries dialog, from the file menu.
