### ISSUE TITLE
[Feature Request] Sorted Output directories

### ISSUE THREAD

**Issue by mad-man111** [openaudible/openaudible#837] opened 2022-01-20 21:54 UTC
Would it be possible to setup the conversion output to be ~/OUTPUT/Author/Serise/BookTitle.m4b

I've tried and failed to write a script that does it based on tags and would be really useful!

Thanks!

**Comment by openaudible** [comment] 2022-01-21 03:57
Its in the works. Duplicate of several feature requests.. Hopefully Q2 2022.

**Closed by openaudible** 2022-01-21 03:57 UTC
