### ISSUE TITLE
Unable to convert aaxc file - missing audible_key/audible_iv pair

### ISSUE THREAD

**Issue by sonicflame17** [openaudible/openaudible#1156] opened 2023-03-13 04:08 UTC
I purchased and downloaded several audio books today, and one is failing to convert to M4B. It's definitely a book I bought and not one of the Audible Premium Plus or otherwise "free" books, and it's also definitely an AAX and not an AAXC file (verified both in Finder and by manually downloading the book from my Audible library). 
![Screen Shot 2023-03-12 at 11 05 32 PM](https://user-images.githubusercontent.com/127711969/224605862-a4f50dc0-b1c7-48bc-b354-f031ad4d090a.png)

Here's the console output:

> INFO: Downloaded /Volumes/Media/OpenAudible/aax/Warriors Super Edition Yellowfang's Secret.AAX bytes=745607854 time=817944 Kbps=890 Warriors Super Edition: Yellowfa
Mar 12, 2023 11:05:02 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -i "/Volumes/Media/OpenAudible/aax/Warriors Super Edition Yellowfang's Secret.AAX" -f ffmetadata - 
Mar 12, 2023 11:05:02 PM org.openaudible.convert.AAXParser updateBookFromAAX
WARNING: product id mismatch for Warriors Super Edition: Yellowfa [BK_HARP_011361] and Warriors Super Edition: Yellowfa file [BK_HARP_011361IN]. File is: /Volumes/Media/OpenAudible/aax/Warriors Super Edition Yellowfang's Secret.AAX
Mar 12, 2023 11:05:02 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Warriors Super Edition: Yellowfa DownloadQueue size:0 remain:0 success:4 fail:0 threads:1
Mar 12, 2023 11:05:04 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:1

**Comment by Echelon101** [comment] 2023-03-13 09:09
Same Problem on Ubuntu 20.04.3 LTS
Log: https://gist.github.com/Echelon101/9b632f9583be4946d43871748dcc2d2b

**Comment by openaudible** [comment] 2023-03-13 16:07
Delete audiobook and download + convert with OpenAudible. Duplicate of #1115 
New beta has improved error handling and message. (Should attempt re-download and get keys)

**Comment by sonicflame17** [comment] 2023-03-13 16:18
Deleted audiobook, downloaded with OpenAudible and failed conversion with the same result.

**Comment by sonicflame17** [comment] 2023-03-13 16:21
@openaudible Issue is not closed- still having the same problem as specified above.

**Comment by openaudible** [comment] 2023-03-13 20:30
Thanks for the log. It does look like you might have two similar books: 
Forward [BK_BRLL_012298DE] and Forward: Stories of Tomorrow (Un file [BK_BRLL_012298JP].
Are they the same?
If you can attempt to reproduce this on the beta, I would appreciate it.
Install beta https://openaudible.org/beta
delete book in question
controls: full library sync
download book
convert book
reply here with result. (send bug from Help Menu if you want to provide additional details.)

**Comment by Echelon101** [comment] 2023-03-16 12:22
I have only one Book named Forward in my Library.
![image](https://user-images.githubusercontent.com/22678948/225615794-f2aa079b-9a83-4436-840d-ed3490bc4397.png)

I'll try to repeat the steps in beta.

**Comment by Echelon101** [comment] 2023-03-16 12:40
Can't select to convert file.
![image](https://user-images.githubusercontent.com/22678948/225618416-cc8aa54e-9839-4c67-a1d1-7f2033a06963.png)
Log: https://gist.github.com/Echelon101/fecaaebdb8dbd2382fd57292b8960a1c

**Comment by openaudible** [comment] 2023-03-16 20:43
Give the latest 3.7 a try.. We've added some code to provide better messages about what is going on.. and should do better getting these files.

**Closed by openaudible** 2023-03-16 20:43 UTC

**Comment by sonicflame17** [comment] 2023-03-19 03:03
> Give the latest 3.7 a try.. We've added some code to provide better messages about what is going on.. and should do better getting these files.

Confirmed working for me in 3.7 now- thank you!
