### ISSUE TITLE
Can't download PDFs

### ISSUE THREAD

**Issue by yeeiser1** [openaudible/openaudible#1230] opened 2023-06-22 18:32 UTC
I am not well versed in code, so I don't know exactly what could have gone wrong but for some reason the program only downloaded 4 PDFs out of 30, the console shows the following:

**Comment by openaudible** [comment] 2023-06-23 03:33
This could be a few things. Make sure you're connected to your account, and that the book is still in your library. Do a "Full Rescan" from the controls menu. Then try again. 
If that doesn't work, try downloading it from the audible web site. Sometimes PDF links get broken. But it may be just that in between the time you did a rescan and the time you tried to get the pdf, that the link expired. Hope that helps.
It does look like the "failed" count is not incrementing.. so there may be a bug on our end on the reporting.. but hopefully a rescan will help resolve the problem. Let us know.

**Comment by yeeiser1** [comment] 2023-06-23 13:20
Did a full rescan and the issue persisted. Went on to the Audible website and tried downloading 5 PDFs to see if the links were dead, they were all functional and was able to download them without any problems.
I thought that maybe the issue is that I have my library on an external drive so I tried redownloading all of it on my C drive but the problem still persists, the program downloads just 4 out 31 PDFs.

**Comment by openaudible** [comment] 2023-06-24 01:18
OK.. We found the problem..
We have posted a beta with a fix:
https://openaudible.org/beta

**Comment by christianmerges** [comment] 2023-06-24 11:07
I can confirm that more pdfs has been downloaded after this beta. Tere is just 5 pdfs missing, which is maybe because of nonexistent books in library anymore. How can i double check this?

**Comment by openaudible** [comment] 2023-06-25 14:16
Open the File Console window and select one of the books with a missing pdf and select Action download pdf. Look at the error message. The error might say forbidden or file not found or invalid file type (maybe it is a zip file?) etc.

**Comment by openaudible** [comment] 2023-06-26 21:06
Fixed in 3.8.1. Also updated chapters and splitting.

**Closed by openaudible** 2023-06-26 21:06 UTC
