### ISSUE TITLE
Download error:No Library Record Found for user. 

### ISSUE THREAD

**Issue by Shark1337** [openaudible/openaudible#669] opened 2021-07-17 13:25 UTC
I can not download any book, my list is downloaded but when I download it, the error appears, if I manage to download a book, I will buy the application because it seems great, but without this functionality it does not work for me, I hope you can help me , I put the error log below

![image](https://user-images.githubusercontent.com/6165744/126038528-91fe823e-5412-4d0f-8485-581d35e67be1.png)

``````
03:22:05.187`	01:00:00.545	needQuery: last=0 new=2
03:22:05.203	01:00:00.561	query start:h_len=0 hash=0 end:h_len=78618 hash=47703484 eq=false Last Query:16;ProgChanged=3,ProgComplete=1,LocChanging=0,LocChanged=1,;same=0;diff=0;url=https://www.audible.es/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=A1RKKUPIHCS9HS&pageId=amzn_audible_ios_privatepool&openid.return_to=https%3A%2F%2Fwww.audible.es%2Fap%2Fmaplanding&openid.assoc_handle=amzn_audible_ios_lap_es&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36423330433236353741353236314230324346453942333441364332463141314531333936313135234132435A4A5A474C4B324A4A564D&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
03:22:05.203	01:00:00.561	pageGood..exiting in 10 seconds...
03:22:05.203	01:00:00.561	waitForPageLoad exit:561 result=h_len=78618 hash=47703484 inspect=Last Query:16;ProgChanged=3,ProgComplete=1,LocChanging=0,LocChanged=1,;same=0;diff=1;url=https://www.audible.es/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=A1RKKUPIHCS9HS&pageId=amzn_audible_ios_privatepool&openid.return_to=https%3A%2F%2Fwww.audible.es%2Fap%2Fmaplanding&openid.assoc_handle=amzn_audible_ios_lap_es&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36423330433236353741353236314230324346453942333441364332463141314531333936313135234132435A4A5A474C4B324A4A564D&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
jul. 17, 2021 3:22:05 P. M. org.openaudible.util.HTMLUtil writeFile
INFORMACIÓN: wrote 4282 to disk:C:\Users\ruben\OpenAudible\tmp\0.txt
jul. 17, 2021 3:22:06 P. M. org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFORMACIÓN: AudibleBrowser setURL: about:blank
jul. 17, 2021 3:22:06 P. M. org.openaudible.desktop.swt.manager.browser.AudibleBrowser closed
INFORMACIÓN: Closed browser...
jul. 17, 2021 3:22:35 P. M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMACIÓN: Command: Console
jul. 17, 2021 3:22:39 P. M. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
ADVERTENCIA: error downloading Lolita: Download error:No Library Record Found for user. for Lolita
jul. 17, 2021 3:22:39 P. M. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
ADVERTENCIA: error downloading Lolita: Download error:No Library Record Found for user. for Lolita
jul. 17, 2021 3:22:41 P. M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMACIÓN: Command: Download
jul. 17, 2021 3:22:41 P. M. org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFORMACIÓN: Added 1 of 1
jul. 17, 2021 3:22:41 P. M. org.openaudible.util.queues.ThreadedQueue run
INFORMACIÓN: Starting job Download Lolita Working.... 1 remain
jul. 17, 2021 3:22:41 P. M. org.openaudible.Audible jobStarted
INFORMACIÓN: DownloadQueue started:Lolita Working.... 1 remain
jul. 17, 2021 3:22:41 P. M. org.openaudible.download.DownloadJob download
INFORMACIÓN: Downloading book: Lolita url=https://cds.audible.es/download?asin=8898425546&cust_id=vVdCYyXhNbPdLuZ_9bmLiAvO-ymYEevlT3D4OYJcqrpJSnRXmKbglUD6tD2ZTg&codec=LC_128_44100_stereo&source=audible_iPhone&type=AUDI
jul. 17, 2021 3:22:42 P. M. org.openaudible.download.DownloadJob helperBodyToURL
GRAVE: helperToURL: No Library Record Found for user.
jul. 17, 2021 3:22:42 P. M. org.openaudible.download.DownloadJob handleError
GRAVE: Error downloading book:Lolita
url=https://cds.audible.es/download?asin=8898425546&cust_id=vVdCYyXhNbPdLuZ_9bmLiAvO-ymYEevlT3D4OYJcqrpJSnRXmKbglUD6tD2ZTg&codec=LC_128_44100_stereo&source=audible_iPhone&type=AUDI
dl=https://cds.audible.es/download?asin=8898425546&cust_id=vVdCYyXhNbPdLuZ_9bmLiAvO-ymYEevlT3D4OYJcqrpJSnRXmKbglUD6tD2ZTg&codec=LC_128_44100_stereo&source=audible_iPhone&type=AUDI
err=Download error:No Library Record Found for user. for Lolita
region=ES
dl_body=No Library Record Found for user.
dl_body error:java.io.IOException: Expected assemble_url
jul. 17, 2021 3:22:42 P. M. org.openaudible.download.DownloadJob download
INFORMACIÓN: Download failed:C:\Users\ruben\OpenAudible\aax\Lolita.1.AAX Lolita
jul. 17, 2021 3:22:42 P. M. org.openaudible.util.queues.ThreadedQueue jobError
INFORMACIÓN: DownloadQueue error processing Download Lolita
java.io.IOException: Download error:No Library Record Found for user. for Lolita
	at org.openaudible.download.DownloadJob.handleError(DownloadJob.java:116)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:227)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:327)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:334)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:480)

jul. 17, 2021 3:22:42 P. M. org.openaudible.Audible jobCompleted
INFORMACIÓN: DownloadQueue completed:Lolita Working.... 1 remain
jul. 17, 2021 3:22:42 P. M. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
ADVERTENCIA: error downloading Lolita: Download error:No Library Record Found for user. for Lolita
jul. 17, 2021 3:22:42 P. M. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString

**Comment by openaudible** [comment] 2021-07-18 13:37
Duplicate of #631 #632 #655

**Closed by openaudible** 2021-07-18 13:37 UTC
