### ISSUE TITLE
Ubuntu - can't connect to Audible

### ISSUE THREAD

**Issue by dcpiccolo** [openaudible/openaudible#782] opened 2021-11-15 17:41 UTC
App is unusable.  When I click to connect with Audible, the browser window opens with the sign-in page, but when I click sign-in, it doesn't load or authenticate.  If at this point I click out of the login browser window (to the open audible window) the contents of the browser window blank out and nothing happens.

**Comment by dcpiccolo** [comment] 2021-11-15 17:43
Image of blank browser window after clicking "sign-in"
![image](https://user-images.githubusercontent.com/84648360/141829061-d68f7cc6-59fa-4bba-99ad-3f77d883a343.png)

**Comment by openaudible** [comment] 2021-11-15 17:45
Unfortunately there is a bug in some of the newer 3rd-party libraries (webkit). 
This is a duplicate of #757 which I've reopened. 
The docker version may be a good alternative at the moment.
https://hub.docker.com/r/openaudible/openaudible

**Comment by kubijo** [comment] 2021-11-15 17:55
The docker version indeed worked-out for me, but certainly isn't painless, even considering that I already have docker setup…
- entering password from a password manager is a major pain
- it screws-up permissions on the state storing home directory

**Comment by openaudible** [comment] 2021-11-15 18:15
Password should be optional...  but yeah, it isn't pretty. 

Unfortunately I have little to no ability to debug someone's newly added bug in the webkit code. Its possible downgrading to an earlier version of the webkit library might help.

There is one other work around I'm considering..

**Comment by kubijo** [comment] 2021-11-15 18:17
I meant password for your Amazon account ... that one is not optional, and I have resorted to getting into the Dockerized system through a file in the `~/OpenAudible` directory  :shrug:

**Comment by openaudible** [comment] 2021-11-17 03:03
Webkit (browser rendering library) was expecting a gstreamer plugin to do closed captions. Those are in a library considered "bad", which are not included in the latest Ubuntu 21.10. 

``` 
sudo apt install gstreamer1.0-plugins-bad
```

According to GStreamer, Bad Plug-ins is a set of plug-ins that aren't up to par compared to the rest. They might be close to being good quality, but they're missing something - be it a good code review, some documentation, a set of tests, a real live maintainer, or some actual wide use.

But installing gstreamer1.0-plugins-bad should fix the issue. 

Duplicate of #757

**Closed by openaudible** 2021-11-17 03:03 UTC
