### ISSUE TITLE
Conversion from AAX to MP3 failing

### ISSUE THREAD

**Issue by jasoncawood** [openaudible/openaudible#25] opened 2018-08-06 17:45 UTC
I've downloaded a few files from my library and am attempting to convert them to MP3 but am returning an error.  libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

I have installed libssl1.0.2  

Ideas?

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

$ sudo apt search libssl
Sorting... Done
Full Text Search... Done

libssl1.0.2/stable,stable,now 1.0.2l-2+deb9u3 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Aug 06, 2018 10:33:09 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Convert
Aug 06, 2018 10:33:09 AM org.openaudible.util.queues.ThreadedQueue$JobThread run
INFO: Starting job convert How to Win Friends & Influence P In progress:1 queue: 0
Aug 06, 2018 10:33:09 AM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:How to Win Friends & Influence P size:0
Aug 06, 2018 10:33:09 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /home/jcawood/OpenAudible/bin/linux_ffmpeg -i /home/jcawood/OpenAudible/aax/BK_SANS_000536.AAX 
Aug 06, 2018 10:33:09 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /home/jcawood/OpenAudible/bin/linux_rcrack /home/jcawood/OpenAudible/bin/tables/audible_byte#4-4_1_10000x1362345_0.rt /home/jcawood/OpenAudible/bin/tables/audible_byte#4-4_0_10000x1362345_0.rt /home/jcawood/OpenAudible/bin/tables/audible_byte#4-4_3_10000x1362345_0.rt /home/jcawood/OpenAudible/bin/tables/audible_byte#4-4_2_10000x1362345_0.rt -h 50f778b8e36c2667e85bf46b0ad275c328a941c2 
Aug 06, 2018 10:33:09 AM org.openaudible.convert.LookupKey lookupKey
INFO: 
Aug 06, 2018 10:33:09 AM org.openaudible.convert.LookupKey lookupKey
INFO: /home/jcawood/OpenAudible/bin/linux_rcrack: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Aug 06, 2018 10:33:09 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:How to Win Friends & Influence P
java.io.IOException: Unable to find expected output: hex:
	at org.openaudible.convert.LookupKey.lookupKey(LookupKey.java:129)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:81)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:90)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:237)
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:119)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:270)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:306)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:256)

Aug 06, 2018 10:33:09 AM org.openaudible.Audible jobCompleted

**Comment by openaudible** [comment] 2018-08-12 18:00
Looks like you have openssl 1.0.2 and rcrack is looking for 1.0.0.
You can try to build it yourself:
https://github.com/inAudible-NG/RainbowCrack-NG
Closing because I can't reproduce.. but feel free to post an answer if you get it working.

**Closed by openaudible** 2018-08-12 18:00 UTC

**Comment by yJun-Chen** [comment] 2021-01-21 01:45
audible_byte#4-4_0_10000x1362345_0.rt，audible_byte#4-4_1_10000x1362345_0.rt，audible_byte#4-4_2_10000x1362345_0.rt，audible_byte#4-4_3_10000x1362345_0.rt 
What characters do these rainbow tables contain? What is the length?
